import * as THREE from 'three';
import {ACTIVITY_SITES} from '../places.js';
import {material,oval,stem,merged} from '../organic.js';

export const ENERGY_ALERT=25;
export function createEnergy(){let value=100,alerted=false;return {get value(){return value;},get low(){return value<=ENERGY_ALERT;},update(dt,{home=false,resting=false,fast=false}={}){value=THREE.MathUtils.clamp(value+dt*(home?6:resting?0:fast?-.1:-.075),0,100);if(value>35)alerted=false;if(value<=ENERGY_ALERT&&!alerted){alerted=true;return true;}return false;},restore(amount){value=Math.min(100,value+amount);if(value>35)alerted=false;}};}
export function inHome(p){return p.x>-37.8&&p.x<-23.5&&p.z>99&&p.z<122.5&&p.y<8;}
const titles={fish:'A quiet moment by the water',potato:'Warm potatoes, small fire',melon:'A watermelon adventure',rabbit:'A rabbit in the grass',kite:'A breeze along the avenue',firework:'Light up the summer sky'};
const questions={fish:'Would you like to fish? Cast, wait for the float, then reel when it dips.',potato:'Roast a potato? Turn it over twice while it cooks.',melon:'Sneak a ripe watermelon? Find one among the vines, then pick it.',rabbit:'Chase a rabbit? Get close enough to gently scoop it up.',kite:'Fly a kite? Pull the line three times and watch it rise.',firework:'Light a firework? Watch the colour bloom over the village.'};
export function siteAvailable(site,environment){const warm=environment.season==='summer'||environment.season==='corn',night=environment.daylight<.15;return site.kind==='melon'?warm:site.kind==='fish'?environment.season!=='winter':site.kind==='firework'?night&&!environment.wet:site.kind==='kite'||site.kind==='potato'?!environment.wet&&environment.weather!=='storm':true;}

export function createAdventure({scene,camera,walk,environment,world,creatures,audio,notice,onHome=()=>{},random=Math.random}){
  const energy=createEnergy(),cooldowns=new Map(),root=new THREE.Group();root.name='Wandering activities';scene.add(root);const hand=new THREE.Group();camera.add(hand);const fireLight=new THREE.PointLight('#ffc879',0,10,2);fireLight.visible=false;scene.add(fireLight);
  let active=false,offer=null,task=null,selectionClock=0,elapsed=0,propsReady=false,lastOutcome='';
  let camp,flames=[],float,line,rod,kite,kiteLine,rocket,burst,burstVelocities=[],fireworkElapsed=0;
  const campPosition=new THREE.Vector3(-156,.2,213);
  const state=()=>({energy:energy.value,low:energy.low,home:inHome(camera.position),offer,task,title:task?titles[task.site.kind]:offer?titles[offer.kind]:'',description:task?.description||questions[offer?.kind]||'',progress:task?Math.min(1,task.progress||0):0,outcome:lastOutcome});
  function ensureProps(){if(propsReady)return;propsReady=true;const rock=material('#7c7c68'),wood=material('#655540');camp=new THREE.Group();camp.position.copy(campPosition);root.add(camp);for(let i=0;i<11;i++)oval(camp,[Math.sin(i*.571)*.56,.06,Math.cos(i*.571)*.56],[.13,.09,.10],rock);for(let i=0;i<4;i++){const a=i*.9;stem(camp,[[-Math.cos(a)*.4,.06,-Math.sin(a)*.4],[Math.cos(a)*.4,.08,Math.sin(a)*.4]],.055,wood);}const potatoMat=material('#c0a17c');for(let i=0;i<3;i++)oval(camp,[.15+i*.09,.11,-.07+i*.05],[.07,.04,.05],potatoMat);
    for(let i=0;i<7;i++){const f=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:i%2?'#ef8e39':'#f6cd78',transparent:true,opacity:.8,depthWrite:false}));f.position.set((random()-.5)*.3,.2,(random()-.5)*.3);f.scale.set(.055,.20,.055);camp.add(f);flames.push(f);}fireLight.position.copy(campPosition).add(new THREE.Vector3(0,.4,0));
    rod=new THREE.Group();stem(rod,[[.28,-.45,-.55],[.48,.05,-1.1],[.57,.4,-1.95]],.011,material('#a18861'));oval(rod,[.28,-.4,-.6],[.025,.08,.025],wood);hand.add(rod);
    float=new THREE.Group();oval(float,[0,.02,0],[.023,.038,.023],material('#e0e1bb'));oval(float,[0,.075,0],[.012,.045,.012],material('#bd6746'));root.add(float);
    line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:'#d5d9c3',transparent:true,opacity:.5}));line.frustumCulled=false;root.add(line);
    kite=new THREE.Group();const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([0,1.1,0,-.7,0,0,0,-.7,.12,0,1.1,0,0,-.7,.12,.7,0,0],3));geo.computeVertexNormals();kite.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#c95e42',side:THREE.DoubleSide,roughness:.8})));stem(kite,[[0,-.7,.14],[0,1.1,0]],.013,wood);stem(kite,[[-.7,0,0],[.7,0,0]],.012,wood);for(let i=0;i<6;i++){const p=oval(kite,[Math.sin(i*.8)*.10,-1-i*.16,.10],[.08,.025,.045],material(i%2?'#d9bb73':'#779887'));p.rotation.z=i*.6;}root.add(kite);kiteLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),line.material);kiteLine.frustumCulled=false;root.add(kiteLine);
    rocket=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,.24,8),material('#b34230'));root.add(rocket);const pos=new Float32Array(140*3),colors=new Float32Array(140*3);for(let i=0;i<140;i++){new THREE.Color().setHSL(i/140,.8,.7).toArray(colors,i*3);}const bg=new THREE.BufferGeometry();bg.setAttribute('position',new THREE.BufferAttribute(pos,3));bg.setAttribute('color',new THREE.BufferAttribute(colors,3));burst=new THREE.Points(bg,new THREE.PointsMaterial({size:.13,vertexColors:true,transparent:true,depthWrite:false,opacity:1,blending:THREE.AdditiveBlending}));burst.frustumCulled=false;root.add(burst);setProps();}
  function setProps(){const kind=task?.site.kind;rod&&(rod.visible=kind==='fish');float&&(float.visible=kind==='fish');line&&(line.visible=kind==='fish');kite&&(kite.visible=kind==='kite');kiteLine&&(kiteLine.visible=kind==='kite');rocket&&(rocket.visible=kind==='firework');burst&&(burst.visible=kind==='firework'&&fireworkElapsed>1.4);for(const f of flames)f.visible=kind==='potato';fireLight.visible=kind==='potato';fireLight.intensity=kind==='potato'?4:0;}
  function finish(message,amount=0){if(!task)return;cooldowns.set(task.site.id,elapsed+90+random()*60);if(task.rabbit){task.rabbit.chasing=false;task.rabbit.home.y=walk.nav.ground??.1;task.rabbit.g.position.y=task.rabbit.home.y;}
    energy.restore(amount);lastOutcome=task.site.kind+(amount?'':'-missed');notice(message+(amount?` · +${amount} energy`:''));task=null;offer=null;selectionClock=4;setProps();}
  function nearestMelon(){let chosen,d=Infinity;for(const m of world?.gardens?.melons||[]){if(!m.ripe||m.regrow>0)continue;const a=Math.hypot(m.mesh.position.x-camera.position.x,m.mesh.position.z-camera.position.z);if(a<d){d=a;chosen=m;}}return {melon:chosen,distance:d};}
  function chooseOffer(){const choices=ACTIVITY_SITES.filter(s=>siteAvailable(s,environment)&&(cooldowns.get(s.id)||0)<=elapsed&&Math.hypot(s.x-camera.position.x,s.z-camera.position.z)<s.radius&&camera.position.y<4);if(!choices.length){offer=null;return;}offer=choices[Math.floor(random()*choices.length)];}
  function waterPoint(){const p=camera.position,points=[];for(const z of walk.nav.waterZones){if(z.shape==='ellipse'){const a=Math.atan2((p.z-z.center[1])/z.radius[1],(p.x-z.center[0])/z.radius[0]);points.push(new THREE.Vector3(z.center[0]+Math.cos(a)*z.radius[0]*.82,.025,z.center[1]+Math.sin(a)*z.radius[1]*.82));}else{const [a,b,c,d]=z.rect;points.push(new THREE.Vector3(THREE.MathUtils.clamp(p.x,a+.6,c-.6),.025,THREE.MathUtils.clamp(p.z,b+.6,d-.6)));}}return points.sort((a,b)=>a.distanceToSquared(p)-b.distanceToSquared(p))[0];}
  function begin(){if(!offer||walk.driving)return false;ensureProps();task={site:offer,time:0,phase:'start',progress:0,presses:0,origin:camera.position.clone(),description:questions[offer.kind]};offer=null;
    if(task.site.kind==='fish'){task.wait=3+random()*4;task.bite=0;float.position.copy(waterPoint());task.description='Line cast. Watch the float… Q reels when it dips.';audio.play('splash');}
    if(task.site.kind==='rabbit'){const candidates=creatures.list.filter(a=>a.kind==='rabbit').sort((a,b)=>a.g.position.distanceToSquared(camera.position)-b.g.position.distanceToSquared(camera.position));task.rabbit=candidates[0];if(!task.rabbit){finish('The rabbit slipped away. Try again later.');return false;}task.rabbit.chasing=true;task.description='Follow the hopping rabbit. Press Q within 1.7 m to gently catch it.';}
    if(task.site.kind==='firework'){fireworkElapsed=0;rocket.position.set(task.site.x,.3,task.site.z);task.launch=new THREE.Vector3(task.site.x,22,task.site.z);audio.play('fuse');}
    setProps();return true;}
  function act(){if(!active||walk.paused)return false;if(!task)return begin();const kind=task.site.kind;
    if(kind==='fish'){if(task.phase==='bite'){const kinds=['Crucian carp','Common carp','Grass carp','Silver carp','Catfish'],catchName=kinds[Math.floor(random()*kinds.length)];audio.play('splash');finish(`${catchName}! A peaceful catch, released back into the water`,16);}else{finish('Reeled too early. The fish swam away.');}return true;}
    if(kind==='potato'){if(task.time-task.lastTurn>2||task.lastTurn===undefined){task.presses++;task.lastTurn=task.time;task.description=`Turned ${Math.min(task.presses,2)}/2 · roasting…`;audio.play('thud');}return true;}
    if(kind==='melon'){const n=nearestMelon();if(n.distance<1.8){n.melon.regrow=150;n.melon.mesh.visible=false;audio.play('pickup');finish('A sweet watermelon break',22);}else task.description=`Find a striped melon · ${Math.ceil(n.distance)} m · Q to pick when close.`;return true;}
    if(kind==='rabbit'){if(Math.hypot(camera.position.x-task.rabbit.g.position.x,camera.position.z-task.rabbit.g.position.z)<1.7){audio.play('pickup');finish('Rabbit caught gently, cuddled, and let go',12);}else task.description='A little closer… Q catches it within 1.7 m.';return true;}
    if(kind==='kite'){if(task.time-(task.lastPull??-2)>1){task.presses++;task.lastPull=task.time;audio.play('flap');task.description=`Line pulled ${Math.min(task.presses,3)}/3 · let the kite settle in the breeze.`;}return true;}
    return true;}
  function skip(){if(task){finish('Taking a break from this activity.');return;}if(offer){cooldowns.set(offer.id,elapsed+45);offer=null;selectionClock=1;}}
  function animateTask(dt,time,elapsedDt){const t=task,kind=t.site.kind;t.time+=elapsedDt;if(!siteAvailable(t.site,environment)){finish('The weather or season changed. Try this activity another time.');return;}if(camera.position.distanceTo(t.origin)>(kind==='rabbit'||kind==='kite'?60:kind==='melon'?35:22)){finish('You wandered away. Another adventure is waiting.');return;}
    if(kind==='fish'){t.progress=t.phase==='bite'?1:t.time/t.wait;float.position.y=.035+Math.sin(time*2)*.018;let newBite=false;if(t.time>=t.wait&&t.phase!=='bite'){t.phase='bite';t.bite=Math.max(2.8,Math.min(20,elapsedDt*1.75));t.description='The float dipped! Press Q now to reel.';audio.play('splash');newBite=true;}if(t.phase==='bite'){float.position.y-=.09;if(!newBite)t.bite-=elapsedDt;if(t.bite<=0){finish('Missed the bite. The fish got away.');return;}}const p=new THREE.Vector3(.57,.4,-1.95);rod.localToWorld(p);line.geometry.attributes.position.setXYZ(0,...p.toArray());line.geometry.attributes.position.setXYZ(1,...float.position.toArray());line.geometry.attributes.position.needsUpdate=true;}
    if(kind==='potato'){t.progress=t.time/12;for(const [i,f] of flames.entries()){f.scale.y=.14+Math.sin(time*11+i)*.07;f.position.y=.18+Math.sin(time*5+i)*.035;}fireLight.intensity=3.8+Math.sin(time*13)*.7;if(t.time>=12)finish(t.presses>=2?'Golden roasted potato, warm from the embers':'A slowly roasted potato',t.presses>=2?26:14);}
    if(kind==='melon'){const n=nearestMelon();t.description=`Find a striped melon · ${Number.isFinite(n.distance)?Math.ceil(n.distance):'–'} m · Q to pick it.`;t.progress=Math.max(0,1-n.distance/20);if(t.time>60)finish('The watermelon adventure can wait.');}
    if(kind==='rabbit'){const a=t.rabbit,p=a.g.position,dx=p.x-camera.position.x,dz=p.z-camera.position.z,d=Math.hypot(dx,dz),fromHome=Math.hypot(p.x-a.home.x,p.z-a.home.z);if(d<7){a.yaw=Math.atan2(dx,dz)+Math.PI+(random()-.5)*.12;}if(fromHome>19)a.yaw=Math.atan2(p.x-a.home.x,p.z-a.home.z);const speed=d<4?1.8:.8,x=p.x-Math.sin(a.yaw)*speed*dt,z=p.z-Math.cos(a.yaw)*speed*dt,f=walk.standAt(x,z,walk.nav.ground);if(f!==undefined)p.set(x,f+Math.max(0,Math.sin(time*9))*.15,z);else a.yaw+=dt*3;a.g.rotation.y=a.yaw;t.description=`Rabbit · ${Math.round(d)} m away · Q to scoop it up.`;t.progress=Math.max(0,1-d/15);if(t.time>50)finish('That quick rabbit slipped away into the grass.');}
    if(kind==='kite'){t.progress=Math.min(t.time/12,t.presses/3);const offset=new THREE.Vector3(-14,11+Math.min(t.presses,3)*2,-20);kite.position.copy(camera.position).add(offset);kite.rotation.set(.25,Math.sin(time*.7)*.4,Math.sin(time*1.2)*.2);kiteLine.geometry.attributes.position.setXYZ(0,camera.position.x+.2,camera.position.y-.4,camera.position.z);kiteLine.geometry.attributes.position.setXYZ(1,...kite.position.toArray());kiteLine.geometry.attributes.position.needsUpdate=true;if(t.time>=12&&t.presses>=3)finish('Your kite found the wind',10);else if(t.time>40)finish('The kite drifts back down.');}
    if(kind==='firework'){fireworkElapsed=t.time;t.progress=t.time/6;if(t.time<=1.4){rocket.position.y=.3+t.time*16;rocket.position.x=t.site.x+Math.sin(t.time*7)*.07;}else{rocket.visible=false;if(!t.exploded){t.exploded=true;audio.play('bang');burstVelocities=Array.from({length:140},()=>{const y=random()*2-1,a=random()*6.28,rr=Math.sqrt(1-y*y),speed=4+random()*4;return new THREE.Vector3(Math.cos(a)*rr,y,Math.sin(a)*rr).multiplyScalar(speed);});burst.visible=true;}const age=t.time-1.4;burst.position.copy(t.launch);for(let i=0;i<140;i++){const v=burstVelocities[i];burst.geometry.attributes.position.setXYZ(i,v.x*age,v.y*age-age*age*.9,v.z*age);}burst.geometry.attributes.position.needsUpdate=true;burst.material.opacity=Math.max(0,1-age/4.5);}if(t.time>6)finish('A little colour in the night sky',10);}
  }
  return {energy,state,act,skip,get offer(){return offer;},get task(){return task;},get active(){return active;},start(){active=true;root.visible=true;hand.visible=true;selectionClock=0;},stop(){if(task)finish('Adventure paused.');offer=null;active=false;root.visible=false;hand.visible=false;fireLight.visible=false;fireLight.intensity=0;},update(dt,time,elapsedDt=dt){if(!active||walk.paused)return;elapsed+=elapsedDt;for(const [id,end] of cooldowns)if(end<elapsed)cooldowns.delete(id);const home=inHome(camera.position);const warning=energy.update(elapsedDt,{home,resting:Boolean(task),fast:walk.axis().fast||Boolean(creatures.held)});if(warning){notice('Energy is low. Head back to your yard, or take a refreshing activity break.');onHome();}if(task)animateTask(dt,time,elapsedDt);else if(!walk.driving&&(selectionClock-=elapsedDt)<=0){selectionClock=1.4;if(!offer||Math.hypot(offer.x-camera.position.x,offer.z-camera.position.z)>offer.radius||!siteAvailable(offer,environment))chooseOffer();}if(walk.driving)offer=null;}
  };
}
