import * as THREE from 'three';
import {ACTIVITY_SITES} from '../places.js';
import {material,oval,stem,merged} from '../organic.js';
import {createFishing} from './fishing.js';

export const ENERGY_ALERT=25;
export function createEnergy(){let value=100,alerted=false;return {get value(){return value;},get low(){return value<=ENERGY_ALERT;},update(dt,{home=false,resting=false,fast=false}={}){value=THREE.MathUtils.clamp(value+dt*(home?6:resting?0:fast?-.1:-.075),0,100);if(value>35)alerted=false;if(value<=ENERGY_ALERT&&!alerted){alerted=true;return true;}return false;},restore(amount){value=Math.min(100,value+amount);if(value>35)alerted=false;}};}
export function inHome(p){return p.x>-37.8&&p.x<-23.5&&p.z>99&&p.z<122.5&&p.y<8;}
const titles={fish:'A quiet moment by the water',potato:'Warm potatoes, small fire',melon:'A watermelon adventure',rabbit:'A rabbit in the grass',kite:'A breeze along the avenue',firework:'Light up the summer sky'};
const questions={fish:'Choose bait, cast a line, read the float, and play the fish carefully back to shore.',potato:'Roast a potato over the embers. Control the heat, brown both sides, and serve it before it burns.',melon:'Sneak through the vines. Move quietly, find a ripe fruit, and hold to pick it.',rabbit:'Follow a rabbit through the grass. Approach quietly and earn its trust before scooping it up.',kite:'Read the gusts. Pull in a gentle breeze, then ease the line when the wind grows strong.',firework:'Choose your firework colour, light the fuse, and watch it bloom over the village.'};
export function siteAvailable(site,environment){const warm=environment.season==='summer'||environment.season==='corn',night=environment.daylight<.15;return site.kind==='melon'?warm:site.kind==='fish'?environment.season!=='winter':site.kind==='firework'?night&&!environment.wet:site.kind==='kite'||site.kind==='potato'?!environment.wet&&environment.weather!=='storm':true;}

export function createAdventure({scene,camera,walk,environment,world,creatures,audio,notice,onHome=()=>{},random=Math.random}){
  const energy=createEnergy(),cooldowns=new Map(),root=new THREE.Group();root.name='Wandering activities';scene.add(root);const hand=new THREE.Group();camera.add(hand);const fireLight=new THREE.PointLight('#ffc879',0,10,2);fireLight.visible=false;scene.add(fireLight);
  let active=false,offer=null,task=null,selectionClock=0,elapsed=0,propsReady=false,lastOutcome='';
  let camp,flames=[],float,line,rod,kite,kiteLine,rocket,burst,burstVelocities=[],fireworkElapsed=0,catchFish,ripple,roastPotato;
  const campPosition=new THREE.Vector3(-156,.2,213);
  const state=()=>({energy:energy.value,low:energy.low,home:inHome(camera.position),offer,task,title:task?titles[task.site.kind]:offer?titles[offer.kind]:'',description:task?.description||questions[offer?.kind]||'',progress:task?Math.min(1,task.progress||0):0,action:task?.action,secondary:task?.secondary,meter:task?.meter,brace:task?.fishing?.view().brace,disabled:task?.disabled,outcome:lastOutcome});
  function ensureProps(){if(propsReady)return;propsReady=true;const rock=material('#7c7c68'),wood=material('#655540');camp=new THREE.Group();camp.position.copy(campPosition);root.add(camp);for(let i=0;i<11;i++)oval(camp,[Math.sin(i*.571)*.56,.06,Math.cos(i*.571)*.56],[.13,.09,.10],rock);for(let i=0;i<4;i++){const a=i*.9;stem(camp,[[-Math.cos(a)*.4,.06,-Math.sin(a)*.4],[Math.cos(a)*.4,.08,Math.sin(a)*.4]],.055,wood);}const potatoMat=material('#c0a17c');for(let i=0;i<3;i++)oval(camp,[.15+i*.09,.11,-.07+i*.05],[.07,.04,.05],potatoMat);
    for(let i=0;i<7;i++){const f=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:i%2?'#ef8e39':'#f6cd78',transparent:true,opacity:.8,depthWrite:false}));f.position.set((random()-.5)*.3,.2,(random()-.5)*.3);f.scale.set(.055,.20,.055);camp.add(f);flames.push(f);}fireLight.position.copy(campPosition).add(new THREE.Vector3(0,.4,0));
    rod=new THREE.Group();stem(rod,[[.28,-.45,-.55],[.48,.05,-1.1],[.57,.4,-1.95]],.011,material('#a18861'));oval(rod,[.28,-.4,-.6],[.025,.08,.025],wood);hand.add(rod);
    float=new THREE.Group();oval(float,[0,.02,0],[.023,.038,.023],material('#e0e1bb'));oval(float,[0,.075,0],[.012,.045,.012],material('#bd6746'));root.add(float);
    line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(Array.from({length:25},()=>new THREE.Vector3())),new THREE.LineBasicMaterial({color:'#e4e8d6',transparent:true,opacity:.8}));line.frustumCulled=false;root.add(line);
    ripple=new THREE.Mesh(new THREE.RingGeometry(.85,1,40),new THREE.MeshBasicMaterial({color:'#f4eed2',transparent:true,opacity:.4,side:THREE.DoubleSide,depthWrite:false}));ripple.rotation.x=-Math.PI/2;root.add(ripple);
    catchFish=new THREE.Group();catchFish.name='Activity fish';const scales=material('#b7b992'),fin=material('#6b856c');oval(catchFish,[0,0,0],[.25,.09,.075],scales);oval(catchFish,[.20,.005,0],[.08,.075,.065],scales);oval(catchFish,[-.27,.015,0],[.08,.11,.025],fin);oval(catchFish,[0,.10,0],[.12,.035,.015],fin);for(const z of [-.064,.064])oval(catchFish,[.24,.023,z],[.014,.014,.006],material('#2b352b'));root.add(catchFish);
    roastPotato=oval(camp,[0,.18,0],[.23,.14,.15],material('#c4a578'));roastPotato.castShadow=true;
    kite=new THREE.Group();const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([0,1.1,0,-.7,0,0,0,-.7,.12,0,1.1,0,0,-.7,.12,.7,0,0],3));geo.computeVertexNormals();kite.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#c95e42',side:THREE.DoubleSide,roughness:.8})));stem(kite,[[0,-.7,.14],[0,1.1,0]],.013,wood);stem(kite,[[-.7,0,0],[.7,0,0]],.012,wood);for(let i=0;i<6;i++){const p=oval(kite,[Math.sin(i*.8)*.10,-1-i*.16,.10],[.08,.025,.045],material(i%2?'#d9bb73':'#779887'));p.rotation.z=i*.6;}root.add(kite);kiteLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),line.material);kiteLine.frustumCulled=false;root.add(kiteLine);
    rocket=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,.24,8),material('#b34230'));root.add(rocket);const pos=new Float32Array(140*3),colors=new Float32Array(140*3);for(let i=0;i<140;i++){new THREE.Color().setHSL(i/140,.8,.7).toArray(colors,i*3);}const bg=new THREE.BufferGeometry();bg.setAttribute('position',new THREE.BufferAttribute(pos,3));bg.setAttribute('color',new THREE.BufferAttribute(colors,3));burst=new THREE.Points(bg,new THREE.PointsMaterial({size:.13,vertexColors:true,transparent:true,depthWrite:false,opacity:1,blending:THREE.AdditiveBlending}));burst.frustumCulled=false;root.add(burst);setProps();}
  function setProps(){const kind=task?.site.kind;rod&&(rod.visible=kind==='fish');float&&(float.visible=kind==='fish');line&&(line.visible=kind==='fish');catchFish&&(catchFish.visible=kind==='fish'&&task.phase==='caught');ripple&&(ripple.visible=kind==='fish');roastPotato&&(roastPotato.visible=kind==='potato');kite&&(kite.visible=kind==='kite');kiteLine&&(kiteLine.visible=kind==='kite');rocket&&(rocket.visible=kind==='firework');burst&&(burst.visible=kind==='firework'&&fireworkElapsed>1.4);for(const f of flames)f.visible=kind==='potato';fireLight.visible=kind==='potato';fireLight.intensity=kind==='potato'?4:0;}
  function finish(message,amount=0){if(!task)return;cooldowns.set(task.site.id,elapsed+90+random()*60);if(task.rabbit){task.rabbit.chasing=false;task.rabbit.home.y=walk.nav.ground??.1;task.rabbit.g.position.y=task.rabbit.home.y;}
    task.fishing?.clear();walk.setActivityPace?.(1);energy.restore(amount);lastOutcome=task.site.kind+(amount?'':'-missed');notice(message+(amount?` · +${amount} energy`:''));task=null;offer=null;selectionClock=4;setProps();}
  function nearestMelon(){let chosen,d=Infinity;for(const m of world?.gardens?.melons||[]){if(!m.ripe||m.regrow>0)continue;const a=Math.hypot(m.mesh.position.x-camera.position.x,m.mesh.position.z-camera.position.z);if(a<d){d=a;chosen=m;}}return {melon:chosen,distance:d};}
  function chooseOffer(){const choices=ACTIVITY_SITES.filter(s=>siteAvailable(s,environment)&&(cooldowns.get(s.id)||0)<=elapsed&&Math.hypot(s.x-camera.position.x,s.z-camera.position.z)<s.radius&&camera.position.y<4);if(!choices.length){offer=null;return;}offer=choices[Math.floor(random()*choices.length)];}
  function waterPoint(power=.5,p=camera.position){const points=[];for(const z of walk.nav.waterZones||[]){if(z.shape==='ellipse'){const a=Math.atan2((p.z-z.center[1])/z.radius[1],(p.x-z.center[0])/z.radius[0]),depth=.95-power*.2;points.push(new THREE.Vector3(z.center[0]+Math.cos(a)*z.radius[0]*depth,.025,z.center[1]+Math.sin(a)*z.radius[1]*depth));}else{const [a,b,c,d]=z.rect,mx=Math.min(1+power*8,(c-a)/2-.01),mz=Math.min(1+power*8,(d-b)/2-.01);points.push(new THREE.Vector3(THREE.MathUtils.clamp(p.x,a+mx,c-mx),.025,THREE.MathUtils.clamp(p.z,b+mz,d-mz)));}}return points.sort((a,b)=>a.distanceToSquared(p)-b.distanceToSquared(p))[0];}
  function begin(){if(!offer||walk.driving)return false;ensureProps();task={site:offer,time:0,phase:'start',progress:0,presses:0,origin:camera.position.clone(),description:questions[offer.kind]};offer=null;
    task.previousPosition=camera.position.clone();task.holding=false;
    if(task.site.kind==='fish'){task.fishing=createFishing(random);task.water=waterPoint();if(!task.water){finish('Find a bank with water nearby.');return false;}task.floatStart=camera.position.clone();task.floatStart.y=.5;float.position.copy(task.water);walk.place(camera.position.x,camera.position.y,camera.position.z,Math.atan2(camera.position.x-task.water.x,camera.position.z-task.water.z),-.18);syncFishing();}
    if(task.site.kind==='potato'){task.sides=[0,0];task.face=0;task.heat='gentle';task.phase='roasting';task.action='Turn potato · Q';task.secondary='Heat: gentle · B';walk.place(camera.position.x,camera.position.y,camera.position.z,Math.atan2(camera.position.x-campPosition.x,camera.position.z-campPosition.z),-.95);}
    if(task.site.kind==='melon'){task.quiet=false;task.alert=0;task.pick=0;task.phase='approach';task.action='Hold to pick · Q';task.secondary='Crouch · B';}
    if(task.site.kind==='rabbit'){const candidates=creatures.list.filter(a=>a.kind==='rabbit').sort((a,b)=>a.g.position.distanceToSquared(camera.position)-b.g.position.distanceToSquared(camera.position));task.rabbit=candidates[0];if(!task.rabbit){finish('The rabbit slipped away. Try again later.');return false;}task.rabbit.chasing=true;task.quiet=false;task.trust=0;task.phase='approach';task.action='Catch gently · Q';task.secondary='Crouch · B';}
    if(task.site.kind==='kite'){task.lift=.3;task.strain=.2;task.phase='flying';task.secondary='Ease line · B';task.action='Pull line · Q';}
    if(task.site.kind==='firework'){task.phase='choose';task.colour=0;task.action='Light the fuse · Q';task.secondary='Colour: meadow gold · B';fireworkElapsed=0;rocket.position.set(task.site.x,.3,task.site.z);task.launch=new THREE.Vector3(task.site.x,22,task.site.z);}
    setProps();return true;}
  function act(){if(!active||walk.paused)return false;if(!task)return begin();const kind=task.site.kind;
    if(kind==='fish'){const result=task.fishing.act();if(result==='release'){audio.play('splash');finish(`${task.fishing.state.catch.name} released back into the water`,16);}else{if(result==='fight')audio.play('hook');if(result==='cast')audio.play('throw');syncFishing();}return true;}
    if(kind==='potato'){if(task.sides.every(s=>s>=.7&&s<1.3)){audio.play('pickup');finish('Both sides golden. A beautifully roasted potato',26);}else{task.face=1-task.face;task.presses++;audio.play('thud');}return true;}
    if(kind==='melon'){task.holding=!task.holding;return true;}
    if(kind==='rabbit'){if(Math.hypot(camera.position.x-task.rabbit.g.position.x,camera.position.z-task.rabbit.g.position.z)<1.7&&task.trust>=.9){audio.play('pickup');finish('The rabbit settled in your hands, then hopped free',12);}else{task.trust=Math.max(0,task.trust-.12);audio.play('puff');}return true;}
    if(kind==='kite'){task.holding=!task.holding;audio.play('flap');return true;}
    if(kind==='firework'&&task.phase==='choose'){task.phase='fuse';task.time=0;task.disabled=true;task.secondary=null;task.action='Stand back…';audio.play('fuse');return true;}
    return true;}
  function skip(){if(task){finish('Taking a break from this activity.');return;}if(offer){cooldowns.set(offer.id,elapsed+45);offer=null;selectionClock=1;}}
  function syncFishing(){if(!task?.fishing)return;const f=task.fishing;Object.assign(task,f.view());task.phase=f.state.phase;}
  function press(){if(!active||walk.paused)return false;if(!task)return begin();if(task.fishing){const p=task.fishing.press();if(p==='release'){finish(`${task.fishing.state.catch.name} released back into the water`,16);}else{if(p==='fight')audio.play('hook');syncFishing();}return true;}if(task.site.kind==='melon'||task.site.kind==='kite'){task.holding=true;return true;}return act();}
  function release(){if(!task)return;const before=task.phase;task.fishing?.release();if(before==='charge')audio.play('throw');task.holding=false;syncFishing();}
  function clearInputs(){task?.fishing?.clear();if(task)task.holding=false;syncFishing();}
  function secondary(){if(!task||walk.paused||!active)return;const kind=task.site.kind;if(task.fishing){task.fishing.secondary();syncFishing();}else if(kind==='potato'){task.heat=task.heat==='gentle'?'hot':'gentle';task.secondary=`Heat: ${task.heat} · B`;}else if(kind==='rabbit'||kind==='melon'){task.quiet=!task.quiet;task.secondary=task.quiet?'Stand up · B':'Crouch · B';}else if(kind==='kite')task.holding=false;else if(kind==='firework'&&task.phase==='choose'){task.colour=(task.colour+1)%3;task.secondary=`Colour: ${['meadow gold','rose pink','river blue'][task.colour]} · B`;const colour=new THREE.Color(['#f5d481','#eaa0c2','#9bd9ed'][task.colour]);for(let i=0;i<140;i++)colour.toArray(burst.geometry.attributes.color.array,i*3);burst.geometry.attributes.color.needsUpdate=true;}}
  function animateTask(dt,time,elapsedDt){const t=task,kind=t.site.kind,playDt=Math.min(.25,elapsedDt);t.time+=playDt;const speed=Math.hypot(camera.position.x-t.previousPosition.x,camera.position.z-t.previousPosition.z)/Math.max(dt,.001);t.previousPosition.copy(camera.position);if(!siteAvailable(t.site,environment)){finish('The weather or season changed. Try this activity another time.');return;}if(camera.position.distanceTo(t.origin)>(kind==='rabbit'||kind==='kite'?60:kind==='melon'?35:22)){finish('You wandered away. Another adventure is waiting.');return;}
    if(kind==='fish'){const f=t.fishing,before=f.state.phase;f.update(elapsedDt);syncFishing();const s=f.state;if(s.phase!==before){if(s.phase==='wait'&&before==='cast'||s.phase==='bite'||s.phase==='caught')audio.play('splash');if(s.phase==='lost')audio.play('snap');}if(t.castPower!==s.power){t.water=waterPoint(s.power,t.origin);t.castPower=s.power;}const target=t.water.clone();target.y=.035;
      float.visible=!['rig','charge','lost','miss','caught'].includes(s.phase);line.visible=float.visible||s.phase==='caught';ripple.visible=float.visible&&s.phase!=='cast';catchFish.visible=s.phase==='fight'||s.phase==='caught';
      if(s.phase==='cast'){const a=Math.min(1,s.age/.8);float.position.lerpVectors(t.floatStart,target,a);float.position.y+=Math.sin(a*Math.PI)*2.4;}else{float.position.copy(target);if(s.phase==='fight'){const toward=t.origin.clone().sub(target);toward.y=0;float.position.add(toward.multiplyScalar(Math.max(0,1-s.distance/s.initialDistance)));float.position.x+=Math.sin(s.age*2)*.3*s.side;}float.position.y=.04+Math.sin(time*2)*.018-(s.phase==='bite'?.11:s.phase==='nibble'?Math.max(0,Math.sin(time*8))*.04:0);}
      const scale=s.phase==='fight'?.6+Math.sin(time*8)*.12:1+(time%1.5)*.5;ripple.position.copy(float.position);ripple.position.y=.065;ripple.scale.setScalar(scale);ripple.material.opacity=s.phase==='fight'?.45:.22;
      rod.rotation.z=s.rodSide*.22+(s.phase==='fight'?Math.sin(time*8)*s.tension*.035:0);rod.rotation.x=s.phase==='charge'?-.4-s.power*.3:s.phase==='fight'?s.tension*.2:0;catchFish.scale.setScalar(s.catch?s.catch.length/45:1);catchFish.position.copy(float.position);catchFish.position.y=-.13;catchFish.rotation.set(0,time*.7,Math.sin(time*9)*.15);
      if(s.phase==='caught'){catchFish.scale.setScalar(Math.min(.85,s.catch.length/45));catchFish.position.set(-.07,.05,-1.2).applyMatrix4(camera.matrixWorld);catchFish.quaternion.copy(camera.quaternion);}
      const p=new THREE.Vector3(.57,.4,-1.95);rod.localToWorld(p);const end=s.phase==='caught'?catchFish.position:float.position;for(let i=0;i<25;i++){const a=i/24,q=p.clone().lerp(end,a);q.y-=Math.sin(a*Math.PI)*(s.phase==='fight'?.05:.3);line.geometry.attributes.position.setXYZ(i,q.x,q.y,q.z);}line.geometry.attributes.position.needsUpdate=true;if(s.phase==='fight'&&s.reeling&&(t.reelSound??0)<t.time){audio.play('reel');t.reelSound=t.time+.28;}}
    if(kind==='potato'){t.sides[t.face]+=playDt*(t.heat==='hot'?.115:.065);const ready=t.sides.every(s=>s>=.7&&s<1.3),b=t.sides[t.face];t.progress=Math.min(1,Math.min(...t.sides)/.7);t.action=ready?'Serve golden potato · Q':'Turn potato · Q';t.description=`Side ${t.face+1}: ${b<.7?'warming':b<1.15?'golden':'getting dark'}. ${ready?'Both sides are ready — serve now!':'Turn at golden; B moves between hot and gentle embers.'}`;t.meter={label:'Browning',value:Math.min(1,b/1.3),detail:`Side 1 ${Math.round(t.sides[0]*100)}% · Side 2 ${Math.round(t.sides[1]*100)}% · golden 70–115%`,danger:b>1.15};roastPotato.rotation.z=THREE.MathUtils.damp(roastPotato.rotation.z,t.face*Math.PI,8,dt);roastPotato.material.color.set(b>.7?'#966438':'#c4a578');for(const [i,f] of flames.entries()){f.scale.y=(t.heat==='hot'?.23:.14)+Math.sin(time*11+i)*.07;f.position.y=.18+Math.sin(time*5+i)*.035;}fireLight.intensity=3.8+Math.sin(time*13)*.7;if(Math.max(...t.sides)>=1.3)finish('A little too charred. Try gentler embers and turn at golden.');}
    if(kind==='melon'){const n=nearestMelon();t.alert=THREE.MathUtils.clamp(t.alert+playDt*(speed>(t.quiet?1.3:.8)?t.quiet?.1:.3:-.18),0,1);if(t.holding&&n.distance<1.8&&speed<.5){t.pick+=playDt/2.2;t.phase='picking';}else{t.pick=Math.max(0,t.pick-playDt*.3);t.phase='approach';}t.description=`${t.quiet?'Crouched':'Standing'} · ${Number.isFinite(n.distance)?Math.ceil(n.distance):'–'} m to ripe fruit. ${t.phase==='picking'?'Picking carefully…':'Move slowly; stop beside a melon and hold Q.'}`;t.progress=t.pick;t.meter={label:'Rustle in the vines',value:t.alert,detail:'Slow steps are quiet. Running attracts attention.',danger:t.alert>.7};if(t.alert>=1)finish('Too much rustling — a startled bird gave you away. Try a quiet approach.');else if(t.pick>=1){n.melon.regrow=150;n.melon.mesh.visible=false;audio.play('pickup');finish('A ripe watermelon picked quietly from the vines',22);}else if(t.time>90)finish('The watermelon adventure can wait.');}
    if(kind==='rabbit'){const a=t.rabbit,p=a.g.position,dx=p.x-camera.position.x,dz=p.z-camera.position.z,d=Math.hypot(dx,dz),fromHome=Math.hypot(p.x-a.home.x,p.z-a.home.z),settled=t.quiet&&speed<1.3&&d<5;
      t.trust=THREE.MathUtils.clamp(t.trust+playDt*(settled?.22:-.32),0,1);if(d<7&&!settled)a.yaw=Math.atan2(dx,dz)+Math.PI+(random()-.5)*.12;if(fromHome>19)a.yaw=Math.atan2(p.x-a.home.x,p.z-a.home.z);const pace=settled?0:d<4?1.8:.8,x=p.x-Math.sin(a.yaw)*pace*dt,z=p.z-Math.cos(a.yaw)*pace*dt,f=walk.standAt(x,z,walk.nav.ground);if(f!==undefined)p.set(x,f+(settled?0:Math.max(0,Math.sin(time*9))*.15),z);else a.yaw+=dt*3;a.g.rotation.y=a.yaw;t.phase=t.trust>=.9?'trust':'approach';t.description=`Rabbit · ${d.toFixed(1)} m away. ${settled?'It is settling. Stay quiet…':'B to crouch; approach slowly or it will hop away.'} ${t.trust>=.9?'Within 1.7 m, Q gently scoops it up.':''}`;t.progress=t.trust;t.meter={label:'Rabbit trust',value:t.trust,detail:t.quiet?'Crouched · slow steps or wait':'Standing · the rabbit is wary',danger:false};if(t.time>90)finish('That quick rabbit slipped away into the grass.');}
    if(kind==='kite'){const gust=Math.sin(t.time*.65)>.5;t.strain=THREE.MathUtils.clamp(t.strain+playDt*(t.holding?(gust?.24:.025):-.24),.08,1);t.lift=THREE.MathUtils.clamp(t.lift+playDt*(t.holding&&!gust?.13:gust&&!t.holding?.035:-.015),.1,1);t.progress=t.lift;t.description=gust?'A strong gust! Ease the line with B or release Q.':'Gentle breeze. Hold Q to pull; release in the next gust. Tap Pull to toggle.';t.action=t.holding?'Stop pulling · Q':'Pull line · Q';t.meter={label:'Kite line tension',value:t.strain,detail:gust?'Strong gust · ease off':'Gentle breeze · pull',danger:t.strain>.72};const offset=new THREE.Vector3(-14,7+t.lift*12,-20);kite.position.copy(camera.position).add(offset);kite.rotation.set(.25,Math.sin(time*.7)*.4,Math.sin(time*1.2)*.2);kiteLine.geometry.attributes.position.setXYZ(0,camera.position.x+.2,camera.position.y-.4,camera.position.z);kiteLine.geometry.attributes.position.setXYZ(1,...kite.position.toArray());kiteLine.geometry.attributes.position.needsUpdate=true;if(t.strain>=1)finish('The gust tangled the kite. Ease off when the wind strengthens.');else if(t.lift>=1)finish('You guided the kite into a steady breeze',10);else if(t.time>80)finish('The kite drifts back down.');}
    if(kind==='firework'){if(t.phase==='choose'){t.description='B changes colour. Q lights the fuse when you are ready.';return;}fireworkElapsed=t.time;t.progress=t.time/6;if(t.time<=1.4){rocket.position.y=.3+t.time*16;rocket.position.x=t.site.x+Math.sin(t.time*7)*.07;}else{rocket.visible=false;if(!t.exploded){t.exploded=true;t.phase='bloom';audio.play('bang');burstVelocities=Array.from({length:140},()=>{const y=random()*2-1,a=random()*6.28,rr=Math.sqrt(1-y*y),speed=4+random()*4;return new THREE.Vector3(Math.cos(a)*rr,y,Math.sin(a)*rr).multiplyScalar(speed);});burst.visible=true;}const age=t.time-1.4;burst.position.copy(t.launch);for(let i=0;i<140;i++){const v=burstVelocities[i];burst.geometry.attributes.position.setXYZ(i,v.x*age,v.y*age-age*age*.9,v.z*age);}burst.geometry.attributes.position.needsUpdate=true;burst.material.opacity=Math.max(0,1-age/4.5);}if(t.time>6)finish('A little colour in the night sky',10);}
  }
  return {energy,state,act,press,release,clearInputs,secondary,aim(side){if(!walk.paused)task?.fishing?.aim(side);},skip,get offer(){return offer;},get task(){return task;},get active(){return active;},start(){active=true;root.visible=true;hand.visible=true;selectionClock=0;},stop(){if(task)finish('Adventure paused.');offer=null;active=false;root.visible=false;hand.visible=false;fireLight.visible=false;fireLight.intensity=0;},update(dt,time,elapsedDt=dt){if(!active)return;if(walk.paused){clearInputs();return;}elapsed+=elapsedDt;for(const [id,end] of cooldowns)if(end<elapsed)cooldowns.delete(id);const home=inHome(camera.position);const warning=energy.update(elapsedDt,{home,resting:Boolean(task),fast:walk.axis().fast||Boolean(creatures.held)});if(warning){notice('Energy is low. Head back to your yard, or take a refreshing activity break.');onHome();}if(walk.driving&&task){finish('Activity packed away for the ride.');return;}if(task)animateTask(dt,time,elapsedDt);else if(!walk.driving&&(selectionClock-=elapsedDt)<=0){selectionClock=1.4;if(!offer||Math.hypot(offer.x-camera.position.x,offer.z-camera.position.z)>offer.radius||!siteAvailable(offer,environment))chooseOffer();}if(walk.driving)offer=null;}
  };
}
