import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:760,height:500}});page.setDefaultTimeout(180000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});mkdirSync('artifacts/world',{recursive:true});
try{
  await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.overview==='ready');await page.locator('[data-entry=fields]').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.game==='on');
  assert.equal(await page.evaluate(()=>window.__viewer.details.gardens.trees.filter(t=>['peach','pear','apple'].includes(t.kind)).length),5);
  await page.evaluate(()=>{const v=window.__viewer;v.environment.setWeather('clear');v.environment.setSeason('summer');v.details.setSeason('summer');v.environment.setHour(14);v.environment.setDaySpeed(0);v.walk.place(-169,1.75,202,Math.PI/2,-.55);});
  await page.waitForFunction(()=>window.__viewer.details.gardens.melons.some(m=>m.ripe&&m.mesh.visible));await page.screenshot({path:'artifacts/world/summer-garden.png'});
  await page.evaluate(()=>window.__viewer.walk.place(-191,1.75,203,Math.PI/2,-.3));await page.screenshot({path:'artifacts/world/vegetables.png'});
  await page.evaluate(()=>{const v=window.__viewer;v.environment.setSeason('green');v.details.setSeason('green');v.walk.place(-249,1.75,162,0,.35);});await page.waitForFunction(()=>window.__viewer.details.gardens.trees.find(t=>t.kind==='peach').blossomRoot.visible);await page.screenshot({path:'artifacts/world/spring-orchard.png'});
  await page.evaluate(()=>{const v=window.__viewer;v.walk.place(-276,1.75,113,-Math.PI/2,-.65);});await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.encounter==='fish');await page.keyboard.press('q');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityPhase==='bite');await page.keyboard.press('q');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityOutcome==='fish');console.log('Fishing interaction passed');
  await page.evaluate(()=>{const v=window.__viewer,f=v.details.gardens.fish.find(f=>Math.abs(f.g.position.x+276)<15);v.walk.place(f.g.position.x,2.5,f.g.position.z+3,0,-.7);});await page.screenshot({path:'artifacts/world/fish-close.png'});
  await page.evaluate(()=>{const v=window.__viewer;v.game.adventure.skip();v.walk.place(-480.8,1.75,241.25,.4,.3);});await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.encounter==='kite');await page.keyboard.press('q');await page.keyboard.press('q');await page.waitForFunction(()=>{const t=window.__viewer.game.adventure.task;return t?.site.kind==='kite'&&t.time-(t.lastPull??-2)>1.1;});await page.keyboard.press('q');await page.waitForFunction(()=>{const t=window.__viewer.game.adventure.task;return t?.site.kind==='kite'&&t.time-(t.lastPull??-2)>1.1;});await page.keyboard.press('q');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityOutcome==='kite');console.log('Kite interaction passed');
  await page.locator('#walk-menu-toggle').click();await page.locator('#walk-summer-night').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.summerNight==='true');await page.evaluate(()=>window.__viewer.walk.place(-464,1.75,242,Math.PI/2,.7));await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.encounter==='firework');await page.keyboard.press('q');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityOutcome==='firework');await page.screenshot({path:'artifacts/world/night-avenue.png'});console.log('Night firework interaction passed');
  assert.deepEqual(errors,[]);console.log('PASS: seasonal gardens/orchard, live fish, fishing, kite, walking summer-night preset and fireworks; no browser errors');
}finally{await browser.close();}
