import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const url=process.env.BASE_URL||'http://127.0.0.1:4173',out='artifacts/coast';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const errors=[];
async function run(phone){const context=await browser.newContext({viewport:phone?{width:390,height:740}:{width:900,height:600},isMobile:phone,hasTouch:phone,deviceScaleFactor:1}),page=await context.newPage();page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.overview==='ready');assert.equal(await page.locator('.map-pin:visible').count(),7,'All village destinations fit the plan');assert.equal(await page.locator('#canvas-host').getAttribute('data-coast'),'ready');await page.screenshot({path:`${out}/${phone?'phone':'desktop'}-plan.png`});
 await page.locator('[data-entry=coast]').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.walkLocation==='coast'&&document.querySelector('#canvas-host').dataset.game==='on');if(await page.evaluate(()=>Boolean(window.__viewer)))assert.ok(await page.evaluate(()=>{const v=window.__viewer;return v.atmosphere.forest.every(p=>!v.walk.inWater(p.x,p.z,4));}),'Distant woodland stays on land');await frame();await page.screenshot({path:`${out}/${phone?'phone':'desktop'}-beach.png`});console.log(`${phone?'Phone':'Desktop'} coast entry and plan passed`);
 await page.locator('[data-tool=gatling]').click();await page.locator('#hud-fire').waitFor({state:'visible'});assert.match(await page.locator('#hud-fire').textContent(),/Hold fireworks/);const dev=await page.evaluate(()=>Boolean(window.__viewer));
 const old=Number(await page.locator('#canvas-host').getAttribute('data-firework-shots')||0),box=await page.locator('#hud-fire').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=(phone?390:900)&&box.y+box.height<=(phone?740:600));
 if(phone){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2,id:1}]});if(dev)await page.evaluate(()=>{const v=window.__viewer;for(let i=0;i<40;i++)v.game.toys.update(.05,i*.05);});else await page.waitForFunction(n=>Number(document.querySelector('#canvas-host').dataset.fireworkShots)>n+2,old);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 else{await page.keyboard.down('p');if(dev)await page.evaluate(()=>{const v=window.__viewer;for(let i=0;i<40;i++)v.game.toys.update(.05,i*.05);});else await page.waitForFunction(n=>Number(document.querySelector('#canvas-host').dataset.fireworkShots)>n+2,old);await page.keyboard.up('p');}
 const shots=Number(await page.locator('#canvas-host').getAttribute('data-firework-shots'));assert.ok(shots>old+2,'Holding launches multiple real rockets');if(dev)await page.evaluate(()=>{const v=window.__viewer;for(let i=0;i<40;i++)v.game.toys.update(.05,i*.05);});else await frame();assert.equal(Number(await page.locator('#canvas-host').getAttribute('data-firework-shots')),shots,'Release stops launch');assert.ok(Number(await page.locator('#canvas-host').getAttribute('data-firework-bursts'))>0);console.log(`${phone?'Touch':'Keyboard'} continuous fire, bursts and release passed`);
 await page.locator('#walk-menu-toggle').click();await page.locator('#walk-summer-night').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.summerNight==='true');
 if(dev){await page.evaluate(()=>{const v=window.__viewer;v.walk.place(463,1.75,130,-Math.PI/2,.3);v.game.toys.select('gatling');v.game.toys.hold(true);for(let i=0;i<20;i++)v.game.toys.update(.05,i*.05);v.game.toys.hold(false);});await frame();}
 await page.screenshot({path:`${out}/${phone?'phone':'desktop'}-night-fireworks.png`});
 await page.locator('#walk-exit').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.game==='off');await page.locator('[data-entry=house]').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.walkLocation==='courtyard');assert.deepEqual(errors,[]);await context.close();}
try{await run(false);if(!process.env.DESKTOP_ONLY)await run(true);writeFileSync(`${out}/${url.includes('127.0.0.1')?'result':'production-result'}.json`,JSON.stringify({pass:true,url,errors,phone:!process.env.DESKTOP_ONLY},null,2));console.log('PASS: coast, seven map pins, Gatling input, day/night and house return; no JS/shader errors.');}finally{await browser.close();}
