import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createEnvironment} from '../src/environment.js';
const scene=new THREE.Scene();scene.background=new THREE.Color();
const camera=new THREE.PerspectiveCamera();camera.position.set(0,2,0);
const sun=new THREE.DirectionalLight(),sky=new THREE.HemisphereLight(),fill=new THREE.DirectionalLight();
const floor=new THREE.Mesh(new THREE.PlaneGeometry(),new THREE.MeshStandardMaterial());
const host={dataset:{}};
const model=new THREE.Group();
function surface(name){const m=new THREE.MeshStandardMaterial({roughness:.8});m.name=name;model.add(new THREE.Mesh(new THREE.BoxGeometry(),m));return m;}
const road=surface('Web ::MAP | concrete roads'),ceiling=surface('Web ::V | Roof clean white ceiling'),furniture=surface('Web ::V | Interior golden desk timber');
const environment=createEnvironment(scene,camera,sun,sky,fill,floor,host);
environment.setModel(model,{shelters:[{rect:[-1,-1,1,1],roof:3.7}]});
environment.setWalking(true);environment.setWeather('rain');environment.update(.1,1);
assert.equal(host.dataset.precipitation,'none','No rain below a roof');
assert.equal(ceiling.roughness,.8,'Ceiling stays dry');assert.equal(furniture.roughness,.8,'Indoor furniture stays dry');
assert.ok(road.roughness<.4,'Road catches wet reflections');
camera.position.y=5.39;environment.update(.1,2);assert.equal(host.dataset.precipitation,'rain','Rain above low roof on terrace');
environment.setWeather('snow');environment.update(.1,3);assert.equal(host.dataset.precipitation,'snow');
environment.setWeather('clear');environment.update(.1,4);assert.equal(host.dataset.precipitation,'none');assert.equal(road.roughness,.8,'Clear weather restores road finish');
environment.setHour(13);environment.update(.1,5);assert.ok(environment.daylight>.95&&sun.intensity>2,'Midday sun');
environment.setHour(22.5);environment.update(.1,6);assert.ok(environment.daylight<.05,'Night after sunset');assert.ok(sun.intensity<.5&&sky.intensity<1,'Night is dim');
environment.setHour(6.2);environment.update(.1,7);assert.ok(sun.position.x>0,'The sun rises in the east');
environment.setHour(12);environment.setDaySpeed(6);environment.update(10,8);assert.ok(Math.abs(environment.hour-13)<.01,'Six hours per minute advances an hour in ten seconds');environment.setDaySpeed(0);
environment.setWeather('storm');environment.update(.1,9);assert.ok(environment.wet&&road.roughness<.4,'Storms soak the roads');
environment.setWeather('fog');environment.update(.1,10);assert.ok(scene.fog.far<200,'Fog closes in');
environment.setWeather('sunset');assert.ok(Math.abs(environment.hour-18.15)<.01,'Sunset preset keeps its golden hour');
console.log('PASS: indoor shelter, terrace precipitation, wet exterior surfaces, dry interiors, restoration, day/night, storm and fog.');
