import assert from 'node:assert/strict';
import {createFishing} from '../src/game/fishing.js';
function hooked(random=()=>.45){const f=createFishing(random);f.press();f.update(1);f.release();assert.equal(f.state.phase,'cast');for(let i=0;i<500&&f.state.phase!=='bite';i++)f.update(.1);assert.equal(f.state.phase,'bite');f.press();f.release();assert.equal(f.state.phase,'fight');return f;}
const f=hooked();let rests=0,surges=0;
for(let i=0;i<2000&&f.state.phase==='fight';i++){if(f.state.cycle){f.release();f.aim(-f.state.side);surges++;}else{f.press();f.aim(0);rests++;}f.update(.05);}
assert.equal(f.state.phase,'caught','Reading rest/surge cues lands a fish');assert.ok(rests&&surges,'Catch needs multiple rest and fight stages');assert.ok(f.state.catch.length>0&&f.state.catch.weight>0);assert.equal(f.act(),'release');
const bad=hooked(()=>.95);bad.press();for(let i=0;i<2000&&bad.state.phase==='fight';i++)bad.update(.05);assert.equal(bad.state.phase,'lost','Holding reel through strong surges can break the line');assert.match(bad.state.reason,/snapped/);bad.act();assert.equal(bad.state.phase,'rig','Failure allows a new cast without ending the outing');
const miss=createFishing(()=>.5);miss.act();let nibble=false;for(let i=0;i<1000&&miss.state.phase!=='miss';i++){miss.update(.1);if(miss.state.phase==='nibble')nibble=true;}assert.ok(nibble,'Nibbles precede the actual bite');assert.equal(miss.state.phase,'miss');miss.act();miss.secondary();assert.equal(miss.state.bait,'worm');
const short=createFishing(),long=createFishing();short.press();short.release();long.press();for(let i=0;i<15;i++)long.update(.2);long.release();assert.ok(long.state.distance>short.state.distance,'Holding longer casts further');
const slow=createFishing(()=>.5);slow.act();slow.update(10);slow.update(10);assert.equal(slow.state.phase,'nibble');slow.update(10);assert.equal(slow.state.phase,'wait','Passive nibbles finish even on slow frames');slow.update(10);assert.equal(slow.state.phase,'bite');assert.ok(slow.state.window>=10,'A slow frame reveals a usable bite window');slow.press();const before=slow.state.tension;slow.press();slow.update(40);assert.ok(Math.abs(slow.state.tension-before)<.1,'Slow frames do not instantly snap a line');slow.clear();slow.update(.1);assert.equal(slow.state.reeling,false,'Pause/blur clears hold and toggle');
const brace=hooked();while(!brace.state.cycle)brace.update(.1);brace.press();brace.update(.1);const tension=brace.state.tension,distance=brace.state.distance;brace.secondary();assert.ok(brace.state.tension<tension&&brace.state.distance>distance,'Giving line trades distance for lower tension');brace.update(.1);assert.equal(brace.state.reeling,false);
console.log('PASS: cast distance, bait, nibbles, bite, successful multi-stage fight, line break, retry, giving line, catch data and slow-frame/input reset.');
