import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {advanceActivity} from './activity-helpers.mjs';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const out='artifacts/interactive';mkdirSync(out,{recursive:true});const url=process.env.BASE_URL||'http://127.0.0.1:4173';const errors=[];let lastPage;
try{
 for(const mobile of [false,true]){
  const ctx=await browser.newContext({viewport:mobile?{width:390,height:740}:{width:760,height:500},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1});const page=await ctx.newPage();lastPage=page;page.setDefaultTimeout(180000);page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const tag=mobile?'phone':'desktop',click=async selector=>mobile?page.locator(selector).tap():page.locator(selector).click();
  await page.goto(url);await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.overview==='ready');await click('[data-map-activity=fish]');await page.locator('[data-activity-entry]').waitFor({state:'visible'});await click('[data-activity-entry]');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.encounter==='fish');await click('#activity-action');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityPhase==='rig');await click('#activity-secondary');assert.match(await page.locator('#activity-description').textContent(),/Worm/);
  const dev=await page.evaluate(()=>Boolean(window.__viewer));
  console.log(`${tag}: rig ready`);await click('#activity-action');await page.waitForFunction(()=>['cast','wait','nibble','bite'].includes(document.querySelector('#canvas-host').dataset.activityPhase));console.log(`${tag}: cast released`);
  if(dev){await page.evaluate(()=>{const v=window.__viewer,a=v.game.adventure;for(let i=0;i<1000&&a.task?.phase!=='bite';i++)a.update(.05,i*.05);v.game.update(0,0,.25);});}
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityPhase==='bite');console.log(`${tag}: bite shown`);await click('#activity-action');console.log(`${tag}: hook tapped`,await page.locator('#canvas-host').getAttribute('data-activity-phase'));await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityPhase==='fight');await page.locator('#activity-meter').waitFor({state:'visible'});assert.match(await page.locator('#activity-meter-label').textContent(),/tension/);
  for(const selector of ['#activity-action','#activity-secondary','[data-activity-aim="-1"]','[data-activity-aim="1"]','#activity-dismiss'])assert.equal(await page.locator(selector).evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),true,`${tag}: ${selector} reachable`);
  await click('#activity-action');if(dev){await advanceActivity(page,.5);assert.equal(await page.evaluate(()=>window.__viewer.game.adventure.task.fishing.state.reeling),true,'Tap-to-toggle reel');}
  await click('#activity-secondary');if(dev){await advanceActivity(page,.1);assert.equal(await page.evaluate(()=>window.__viewer.game.adventure.task.fishing.state.reeling),false,'Give line stops reeling');}
  await page.screenshot({path:`${out}/${tag}-fishing.png`});console.log(`${tag}: real map entry, bait, cast, hook, touch/click reel and give-line controls passed`);
  if(dev){
   // Input driven hold/release, including actual touch pointer events.
   if(mobile){const cdp=await ctx.newCDPSession(page),r=await page.locator('#activity-action').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2,id:1}]});await advanceActivity(page,.1);assert.equal(await page.evaluate(()=>window.__viewer.game.adventure.task.fishing.state.holding),true);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
   else{await page.keyboard.down('q');await advanceActivity(page,.1);assert.equal(await page.evaluate(()=>window.__viewer.game.adventure.task.fishing.state.holding),true);await page.keyboard.up('q');}
   await page.locator('#walk-menu-toggle')[mobile?'tap':'click']();await page.evaluate(()=>{const v=window.__viewer;v.game.update(0,0,.25);});assert.equal(await page.evaluate(()=>window.__viewer.game.adventure.task.fishing.state.reeling),false,'Menu clears held and toggled reel');await click('#walk-resume');
   await page.evaluate(()=>{const v=window.__viewer,a=v.game.adventure;for(let i=0;i<1800&&a.task?.phase==='fight';i++){const s=a.task.fishing.state;if(s.cycle){a.clearInputs();a.aim(-s.side);}else a.press();a.update(.05,i*.05);}v.game.update(0,0,.25);});await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityPhase==='caught');assert.match(await page.locator('#activity-description').textContent(),/cm.*kg/);await page.screenshot({path:`${out}/${tag}-catch.png`});await click('#activity-action');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityOutcome==='fish');
   if(!mobile){await page.evaluate(()=>{const v=window.__viewer;v.environment.setSeason('summer');v.environment.setWeather('clear');v.walk.place(-154.5,1.75,213);v.game.adventure.update(.1,0,5);v.game.update(0,0,.25);});await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.encounter==='potato');await click('#activity-action');await click('#activity-secondary');await advanceActivity(page,7);await click('#activity-action');await advanceActivity(page,7);await page.evaluate(()=>window.__viewer.walk.pause(true));assert.match(await page.locator('#activity-action').textContent(),/Serve/);await page.screenshot({path:`${out}/potato.png`});await page.evaluate(()=>window.__viewer.walk.pause(false));await click('#activity-action');await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.activityOutcome==='potato');console.log('Desktop catch/release, pause and cooking passed');}
  }else await click('#activity-dismiss');
  await ctx.close();
 }
 assert.deepEqual(errors,[]);writeFileSync(`${out}/${url.includes('127.0.0.1')?'result':'production-result'}.json`,JSON.stringify({pass:true,url,errors},null,2));console.log('PASS: desktop and phone interactive activity UI, no JavaScript/shader errors.');
}catch(e){console.log('FAILED',e.message,errors);if(lastPage&&!lastPage.isClosed()){console.log('Failure state',await lastPage.locator('#canvas-host').evaluate(el=>({phase:el.dataset.activityPhase,activity:el.dataset.activity,encounter:el.dataset.encounter,text:document.querySelector('#activity-description').textContent})));await lastPage.screenshot({path:`${out}/failure.png`});}throw e;}finally{await browser.close();}
