import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.BASE_URL || 'http://127.0.0.1:4173';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto(url,{waitUntil:'networkidle',timeout:60000});
  await page.locator('#scene-image').evaluate(im=>im.decode());
  assert.match(await page.title(),/SmallVillage/);
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.locator('[data-image="alley"]').click();
  assert.equal(await page.locator('#view-title').textContent(),'The familiar way home');
  await page.locator('[data-model="village"]').click();
  assert.match(await page.locator('#scene-image').getAttribute('src'),/village/);
  await page.locator('[data-image="entrance"]').click();
  assert.equal(await page.locator('[data-model="house"]').getAttribute('aria-pressed'),'true');
  await page.locator('#three-mode').click();
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.loadedModel==='house',{},{timeout:120000});
  await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
  await page.screenshot({path:'test-results/house-3d.png',fullPage:false});
  await page.locator('[data-view="top"]').click();
  assert.equal(await page.locator('[data-view="top"]').getAttribute('class'),'active');
  await page.locator('[data-model="village"]').click();
  await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.loadedModel==='village',{},{timeout:120000});
  await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
  await page.screenshot({path:'test-results/village-3d.png',fullPage:false});
  await page.locator('#render-mode').click();
  assert.equal(await page.locator('#scene-image').isVisible(),true);
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-image="courtyard"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile horizontal overflow');
  await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  const fallback=await browser.newPage({viewport:{width:390,height:844}});
  await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){if(String(type).startsWith('webgl'))return null;return original.call(this,type,...rest);};});
  await fallback.goto(url,{waitUntil:'networkidle'});await fallback.locator('#three-mode').click();
  await fallback.waitForFunction(()=>document.querySelector('#interaction-hint').textContent.includes('could not open'));
  assert.equal(await fallback.locator('#scene-image').isVisible(),true);
  const result={url,passed:true,checks:['Desktop rendering','Gallery views','Scene selection consistency','House GLB load','Camera preset','Village GLB load','Return to renders','Mobile no horizontal overflow','WebGL failure fallback','No unexpected page errors']};
  await writeFile('test-results/smoke.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
} finally {await browser.close();}
