import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const errors=[],out='artifacts/tools';mkdirSync(out,{recursive:true});const url=process.env.BASE_URL||'http://127.0.0.1:4173';
try{
 const context=await browser.newContext({viewport:{width:760,height:500}}),page=await context.newPage();page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.overview==='ready');await page.locator('[data-entry=house]').click();await page.waitForFunction(()=>document.querySelector('#canvas-host').dataset.game==='on');await page.keyboard.press('2');await page.locator('#hud-fire').waitFor({state:'visible'});assert.match(await page.locator('#hud-fire').textContent(),/Squirt/);console.log('Visible desktop water trigger');
 const dev=await page.evaluate(()=>Boolean(window.__viewer));
 if(dev){await page.evaluate(()=>{const v=window.__viewer,emit=v.game.toys.fire;/* Input assertions observe real projectiles through the public toy controller. */v.game.toys.cancelHold();v.game.toys.update(.6,0);});}
 const trigger=await page.locator('#hud-fire').boundingBox();await page.mouse.move(trigger.x+trigger.width/2,trigger.y+trigger.height/2);await page.mouse.down();if(dev){assert.ok(await page.evaluate(()=>window.__viewer.game.toys.projectiles.some(p=>p.kind==='water')),'Visible trigger emits actual water');}await page.mouse.up();
 if(dev){await page.evaluate(()=>{const v=window.__viewer;v.game.toys.clear();v.game.toys.update(.6,0);});await page.mouse.click(250,200);assert.ok(await page.evaluate(()=>window.__viewer.game.toys.projectiles.some(p=>p.kind==='water')),'Free-look left click emits actual water');await page.evaluate(()=>{const v=window.__viewer;v.game.toys.clear();v.game.toys.update(.6,0);});await page.mouse.move(250,200);await page.mouse.down();await page.mouse.move(280,210);await page.mouse.up();assert.equal(await page.evaluate(()=>window.__viewer.game.toys.projectiles.length),0,'Looking does not fire');}
 await page.keyboard.press('1');await page.keyboard.down('p');if(dev)await page.evaluate(()=>window.__viewer.game.toys.update(.5,0));await page.keyboard.up('p');if(dev)assert.ok(await page.evaluate(()=>window.__viewer.game.toys.projectiles.some(p=>p.kind==='slingshot')),'P draw/release fires the slingshot');
 await page.screenshot({path:`${out}/desktop.png`});console.log('Desktop water, click versus drag and keyboard slingshot passed');
 await page.setViewportSize({width:390,height:740});const cdp=await context.newCDPSession(page);await page.keyboard.press('2');if(dev)await page.evaluate(()=>window.__viewer.game.toys.update(.7,0));const r=await page.locator('#hud-fire').boundingBox();assert.ok(r.x>=0&&r.y>=0&&r.x+r.width<=390&&r.y+r.height<=740);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2,id:2}]});if(dev)assert.ok(await page.evaluate(()=>window.__viewer.game.toys.projectiles.some(p=>p.kind==='water')),'Touch trigger emits water');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.screenshot({path:`${out}/phone.png`});assert.deepEqual(errors,[]);writeFileSync(`${out}/${dev?'result':'production-result'}.json`,JSON.stringify({pass:true,url,errors},null,2));console.log('PASS: desktop and narrow-screen touch tools; no JavaScript or shader errors.');
}finally{await browser.close();}
