import * as THREE from 'three';
import {GARDEN_PLOTS} from './places.js';
import {seeded,material,oval,stem,leaf,leafGeometry,lotusLeaf,merged,instances} from './organic.js';
import {createPlantingMask} from './planting.js';
import {createWetland} from './wetland.js';

function melonMaterial(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d');x.fillStyle='#76964c';x.fillRect(0,0,256,128);for(let j=0;j<12;j++){x.fillStyle='#315f35';x.beginPath();for(let y=0;y<=128;y+=4){const a=j*22+Math.sin(y*.06+j)*3;x.lineTo(a,y);}for(let y=128;y>=0;y-=4)x.lineTo(j*22+7+Math.sin(y*.06+j)*3,y);x.closePath();x.fill();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map:t,roughness:.67,bumpMap:t,bumpScale:.004});}
export function createGardens({parent,scene,environment,nav}){
  const root=new THREE.Group();root.name='Vegetable gardens and waterside ecology';parent.add(root);const r=seeded(942),mask=createPlantingMask(nav);let season='green';const plots=[],melons=[],trees=[],flowers=[],fish=[],fireflies=[];
  const greens=[material('#477141'),material('#688648'),material('#7b9652')],wood=material('#70624b'),soil=material('#817451'),flowerMat=material('#e8ca89'),red=material('#b95434'),pepper=material('#759546'),melonMat=melonMaterial();
  const soilCanvas=document.createElement('canvas');soilCanvas.width=soilCanvas.height=128;const sx=soilCanvas.getContext('2d');sx.fillStyle='#bfb9a3';sx.fillRect(0,0,128,128);for(let i=0;i<1800;i++){sx.fillStyle=i%3?'#dad4bc88':'#68655366';sx.fillRect(r()*128,r()*128,1+r()*3,1+r()*2);}const soilTexture=new THREE.CanvasTexture(soilCanvas);soilTexture.wrapS=soilTexture.wrapT=THREE.RepeatWrapping;soilTexture.repeat.set(4,4);soilTexture.colorSpace=THREE.SRGBColorSpace;soil.map=soilTexture;soil.bumpMap=soilTexture;soil.bumpScale=.022;
  function template(kind,variant){const g=new THREE.Group(),m=greens[variant%3];if(kind==='melon'){for(let j=0;j<5;j++){const a=j*2.4+variant*.5;stem(g,[[0,.03,0],[Math.sin(a)*.35,.055,Math.cos(a)*.35],[Math.sin(a+.3)*.9,.07,Math.cos(a+.3)*.9]],.012,m);for(let k=0;k<5;k++)leaf(g,[Math.sin(a)*k*.19,.08,Math.cos(a)*k*.19],.12,.28,a+k,m,.35,.25);oval(g,[Math.sin(a)*.5,.095,Math.cos(a)*.5],[.025,.016,.025],flowerMat);}}
    else if(kind==='cabbage'){oval(g,[0,.22,0],[.18,.18,.18],greens[2]);for(let j=0;j<14;j++){const a=j*2.4;leaf(g,[Math.sin(a)*.1,.08,Math.cos(a)*.1],.16,.43,a,m,.12,-.6-(j%3)*.25);}}
    else{const potato=kind==='potato',tomato=kind==='tomato',cucumber=kind==='cucumber',height=potato?.48:cucumber?1.4:.86;
      stem(g,[[0,0,0],[.03,height*.5,.025],[0,height,0]],.015,m);
      for(let j=0;j<9;j++){const a=j*2.4+variant,y=.09+j*(height*.085),x=Math.sin(a)*.10,z=Math.cos(a)*.10;stem(g,[[0,y,0],[x,y+.02,z]],.006,m);leaf(g,[x,y,z],potato?.08:.07,potato?.19:.24,a,m,tomato?.25:0,.15+(j%3)*.3);
        if(j%3===0&&!potato){if(cucumber){const f=oval(g,[x*1.6,y-.06,z*1.6],[.04,.15,.04],greens[0]);f.rotation.z=.2;}else if(tomato)oval(g,[x*1.8,y-.025,z*1.8],[.067,.059,.063],red);else{const f=oval(g,[x*1.6,y-.04,z*1.6],[.035,.085,.032],j%2?red:pepper);f.rotation.z=.3;}oval(g,[x*1.7,y+.015,z*1.7],[.025,.01,.025],m);}}
      if(potato)for(let j=0;j<3;j++){const a=j*2.4;oval(g,[Math.sin(a)*.1,height-.03,Math.cos(a)*.1],[.025,.018,.025],material(variant%2?'#c5b4d2':'#f0e6ce'));}
      if(cucumber){stem(g,[[-.25,0,.2],[-.2,1.55,.2]],.019,wood);stem(g,[[.25,0,.2],[.2,1.55,.2]],.019,wood);stem(g,[[-.2,1.2,.2],[.2,1.2,.2]],.016,wood);}}
    return merged(g);}
  for(const plot of GARDEN_PLOTS){const [x0,z0,x1,z1]=plot.rect,bed=new THREE.Mesh(new THREE.BoxGeometry(x1-x0,.09,z1-z0),soil);bed.position.set((x0+x1)/2,.11,(z0+z1)/2);bed.receiveShadow=true;root.add(bed);const group=new THREE.Group();root.add(group);const variants=[[],[],[]],spacing=plot.kind==='melon'?1.65:plot.kind==='cucumber'?1.15:plot.kind==='potato'?.78:.90;
    for(let x=x0+.7;x<x1-.4;x+=spacing)for(let z=z0+.6;z<z1-.4;z+=spacing){if(r()<.06)continue;const p={x:x+(r()-.5)*.35,z:z+(r()-.5)*.4,y:.16,angle:r()*6.28,scale:.75+r()*.45,tint:new THREE.Color().setHSL(.25,.2,.82+r()*.16)};if(!mask.land(p.x,p.z,.4))continue;variants[Math.floor(r()*3)].push(p);
      if(plot.kind==='melon'&&r()>.28){const fruit=new THREE.Mesh(new THREE.SphereGeometry(1,16,10),melonMat);fruit.position.set(p.x+.2,.33,p.z-.15);fruit.rotation.set(r(),r()*6.28,r()*.3);const s=.2+r()*.11;fruit.scale.set(s,.20+r()*.1,s*1.25);fruit.castShadow=true;group.add(fruit);melons.push({mesh:fruit,ripe:false,regrow:0});}}
    for(let i=0;i<3;i++)group.add(instances(template(plot.kind,i),variants[i]));const moundTemplate=new THREE.Group();oval(moundTemplate,[0,0,0],[spacing*.4,.075,spacing*.35],soil);root.add(instances(merged(moundTemplate),variants.flat().map(p=>({...p,y:.16}))));plots.push({...plot,group,bed});}
  // Mature trees have irregular spreading crowns, forked trunks and genuinely curved leaves.
  const treeHomes=[[-249,156,'peach'],[-240,167,'pear'],[-247,179,'apple'],[-292,84,'willow'],[-251,72,'willow'],[-485,224,'paulownia'],[-424,228,'scholar'],[-151,134,'paulownia'],[12,110,'scholar'],[-435,-17,'scholar'],[-222,189,'peach'],[-193,185,'pear']];
  // Two orchard groves and a handful of shade groups; keep the main grain fields open.
  for(let i=0;i<15;i++)treeHomes.push([-254+(i%5)*7.5+(r()-.5)*2,147+Math.floor(i/5)*12+(r()-.5)*2,['peach','pear','apple','jujube'][i%4]]);
  for(const [x,z,kind] of [[-494,268,'paulownia'],[-480,274,'scholar'],[-462,266,'elm'],[-292,105,'willow'],[-297,76,'willow'],[-292,55,'elm'],[-125,-181,'willow'],[-91,-181,'scholar'],[17,166,'elm'],[20,195,'paulownia']])treeHomes.push([x,z,kind]);
  const occupied=[];
  for(const [desiredX,desiredZ,kind] of treeHomes){const safe=mask.tree(desiredX,desiredZ,occupied);if(!safe)continue;const [x,z]=safe;occupied.push(safe);const fruitTree=['peach','pear','apple','jujube'].includes(kind),tree=new THREE.Group();tree.position.set(x,.1,z);root.add(tree);const height=fruitTree?3.1+r():7.5+r()*4,trunk=fruitTree?.12:.30;const frame=new THREE.Group();stem(frame,[[0,0,0],[.14,height*.4,.06],[-.15,height*.8,0]],trunk,wood);const positions=[];
    for(let j=0;j<9;j++){const a=r()*6.28,extent=(fruitTree?1.6:3.3)+r()*2,y=height*(.5+r()*.3),tip=[Math.sin(a)*extent,y+1+r(),Math.cos(a)*extent];stem(frame,[[0,height*.4,0],[tip[0]*.5,y,tip[2]*.5],tip],trunk*.32,wood);
      for(let k=0;k<45;k++){const b=r()*6.28,rr=Math.sqrt(r())*(fruitTree?1.2:2);positions.push({x:tip[0]+Math.cos(b)*rr,y:tip[1]+(r()-.5)*2,z:tip[2]+Math.sin(b)*rr,angle:r()*6.28,tilt:kind==='willow'?1.2+r()*.5:(r()-.5)*1.8,roll:(r()-.5)*1.2,scale:.75+r()*.8});}}
    tree.add(merged(frame));const l=new THREE.Mesh(leafGeometry(kind==='willow'?.035:kind==='paulownia'?.23:.16,kind==='willow'?.5:kind==='paulownia'?.48:.35,kind==='elm'?.16:kind==='paulownia'?.05:0),greens[0].clone()),leafTemplate=new THREE.Group();leafTemplate.add(l);const canopy=instances(leafTemplate,positions);tree.add(canopy);
    // Painted crown masses sit inside the individual leaves, making complete readable silhouettes.
    const masses=new THREE.Group(),massMat=greens[1].clone();for(let j=0;j<9;j++){const cloud=positions.slice(j*45,(j+1)*45),centre=cloud.reduce((v,p)=>v.add(new THREE.Vector3(p.x,p.y,p.z)),new THREE.Vector3()).multiplyScalar(1/45),mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),massMat);mesh.position.copy(centre);mesh.scale.set(fruitTree?.82:1.35,kind==='willow'?1.65:fruitTree?.72:1.10,fruitTree?.82:1.35);mesh.rotation.set(r()*.5,r()*6.28,r()*.5);masses.add(mesh);}canopy.add(merged(masses));
    const fruitRoot=new THREE.Group(),blossomRoot=new THREE.Group();tree.add(fruitRoot,blossomRoot);
    if(fruitTree){const f=new THREE.Group(),fm=material(kind==='peach'?'#dc9683':kind==='pear'?'#b9ac56':kind==='jujube'?'#8b4934':'#b9503d');oval(f,[0,-.07,0],kind==='pear'?[.08,.09,.08]:kind==='jujube'?[.033,.045,.033]:[.09,.08,.09],fm);if(kind==='pear')oval(f,[0,.015,0],[.045,.06,.045],fm);stem(f,[[0,.04,0],[.012,.1,.01]],.006,wood);fruitRoot.add(instances(merged(f),positions.filter((_,i)=>i%4===0)));const bloom=new THREE.Group(),bm=material(kind==='peach'?'#e3afba':'#eee9d9');for(let k=0;k<5;k++){const a=k*1.256;oval(bloom,[Math.sin(a)*.038,0,Math.cos(a)*.038],[.033,.013,.033],bm);}oval(bloom,[0,.013,0],[.014,.009,.014],flowerMat);blossomRoot.add(instances(merged(bloom),positions.filter((_,i)=>i%3===0)));}trees.push({tree,canopy,fruitRoot,blossomRoot,height,kind});}
  // Irregular soft banks, grass tufts, rounded stones, reeds and small seasonal flowers.
  const stone=material('#969a80'),bank=material('#99aa72'),pink=material('#d49d9d');const bankPieces=new THREE.Group(),flowerTemplate=new THREE.Group();stem(flowerTemplate,[[0,0,0],[.025,.36,0]],.006,greens[0]);for(let j=0;j<5;j++)oval(flowerTemplate,[Math.sin(j*1.256)*.042,.36,Math.cos(j*1.256)*.042],[.03,.014,.03],flowerMat);const flowerPts=[];
  for(const zone of nav.waterZones){const pts=[];if(zone.shape==='ellipse'){for(let j=0;j<95;j++){const a=r()*6.28;pts.push([zone.center[0]+Math.cos(a)*(zone.radius[0]+.4+r()*1.2),zone.center[1]+Math.sin(a)*(zone.radius[1]+.5+r()*.8)]);}const lotusRoot=new THREE.Group();root.add(lotusRoot);for(let j=0;j<24;j++){const a=r()*6.28,rad=.76+r()*.12,px=zone.center[0]+Math.cos(a)*zone.radius[0]*rad,pz=zone.center[1]+Math.sin(a)*zone.radius[1]*rad;stem(lotusRoot,[[px,-.13,pz],[px+.02,.65,pz]],.013,greens[0]);const pad=new THREE.Mesh(lotusLeaf(.3+r()*.17),greens[1]);pad.position.set(px,.55,pz);pad.rotation.set((r()-.5)*.3,a,(r()-.5)*.3);lotusRoot.add(pad);if(j%3===0){for(let k=0;k<10;k++){const a=k*.628;const petal=oval(lotusRoot,[px+Math.sin(a)*.10,.76,pz+Math.cos(a)*.10],[.055,.025,.13],pink);petal.rotation.set(-.35,a,0);}oval(lotusRoot,[px,.78,pz],[.05,.03,.05],flowerMat);}}flowers.push(lotusRoot);}
    else{const [x0,z0,x1,z1]=zone.rect,len=Math.max(x1-x0,z1-z0);for(let j=0;j<len;j+=1.4+r()*2.5){const t=j/len,s=r()>.5?1:-1;pts.push(x1-x0>z1-z0?[x0+t*(x1-x0),s>0?z1+.3+r()*.8:z0-.3-r()*.8]:[s>0?x1+.3+r()*.8:x0-.3-r()*.8,z0+t*(z1-z0)]);}}
    for(const [x,z] of pts){if(!mask.land(x,z,.8))continue;oval(bankPieces,[x,.045,z],[.5+r()*.5,.07,.45+r()*.5],bank);if(r()<.5)oval(bankPieces,[x+r()*.4,.12,z],[.09+r()*.19,.07+r()*.08,.12+r()*.15],stone);if(r()<.5)flowerPts.push({x:x+(r()-.5),z:z+(r()-.5),y:.11,scale:.55+r()*.8,angle:r()*6.28});}}
  const wetland=createWetland({parent:root,nav,environment});root.add(merged(bankPieces));const smallFlowers=instances(merged(flowerTemplate),flowerPts);root.add(smallFlowers);flowers.push(smallFlowers);
  // These common regional fish are representative additions, not a survey of this village.
  const kinds=['Crucian carp','Common carp','Grass carp','Silver carp','Catfish'];
  const fishZones=nav.waterZones.filter(v=>v.shape==='ellipse'||v.rect[2]-v.rect[0]>5&&v.rect[3]-v.rect[1]>4);
  for(const [zi,zone] of fishZones.entries())for(let j=0;j<12;j++){const kind=kinds[j%5],g=new THREE.Group(),fm=material(j%5===1?'#a08d58':j%5===4?'#636c55':'#8ba498');oval(g,[0,0,0],[.085,.085,j%5===2?.33:.24],fm);const tail=new THREE.Mesh(new THREE.ConeGeometry(.105,.18,3),fm);tail.rotation.x=Math.PI/2;tail.position.z=.27;g.add(tail);for(const s of [-1,1]){const fin=oval(g,[s*.065,-.025,0],[.065,.013,.12],fm);fin.rotation.y=s*.5;oval(g,[s*.058,.03,-.17],[.01,.009,.01],material('#213b32'));}const top=oval(g,[0,.085,.04],[.01,.04,.12],fm);if(kind==='Catfish')for(const s of [-1,1])stem(g,[[s*.035,0,-.20],[s*.11,-.035,-.25]],.002,fm);root.add(g);const cx=zone.shape==='ellipse'?zone.center[0]:(zone.rect[0]+zone.rect[2])/2,cz=zone.shape==='ellipse'?zone.center[1]:(zone.rect[1]+zone.rect[3])/2,rx=zone.shape==='ellipse'?zone.radius[0]*.75:(zone.rect[2]-zone.rect[0])*.38,rz=zone.shape==='ellipse'?zone.radius[1]*.75:(zone.rect[3]-zone.rect[1])*.35;fish.push({g,tail,kind,cx,cz,rx,rz,phase:r()*6.28,speed:.12+r()*.18,size:.6+r()*.9});g.scale.setScalar(fish.at(-1).size);}
  const flyGeo=new THREE.BufferGeometry(),flyPositions=new Float32Array(80*3);flyGeo.setAttribute('position',new THREE.BufferAttribute(flyPositions,3));const flies=new THREE.Points(flyGeo,new THREE.PointsMaterial({color:'#e7ee96',size:.06,transparent:true,opacity:.85,depthWrite:false}));flies.frustumCulled=false;root.add(flies);for(let i=0;i<80;i++)fireflies.push({x:-278+r()*30,z:70+r()*45,phase:r()*6.28});
  function setSeason(value){season=value;greens.forEach((m,i)=>m.color.set(value==='corn'?['#80794b','#939054','#7f8b4e'][i]:['#477141','#688648','#7b9652'][i]));for(const p of plots){const winter=value==='winter';p.group.visible=!winter||p.kind==='cabbage';p.group.scale.y=value==='green'&&p.kind!=='potato'&&p.kind!=='cabbage'?.45:1;p.group.position.y=.16*(1-p.group.scale.y);p.bed.material.color.set(winter?'#babba5':'#817451');}for(const t of trees){t.canopy.visible=value!=='winter';t.canopy.traverse(o=>{if(o.material)o.material.color.set(value==='corn'?'#ac9962':'#658e48');});t.fruitRoot.visible=value===(t.kind==='peach'?'summer':'corn');t.blossomRoot.visible=value==='green';}for(const f of flowers)f.visible=value==='summer'||value==='green';for(const m of melons){m.ripe=value==='summer'||value==='corn';m.mesh.visible=m.ripe&&m.regrow<=0;}}
  return {root,plots,melons,fish,trees,wetland,setSeason,update(dt,time,camera){wetland.update(dt,time,camera,season);for(const t of trees){t.tree.visible=camera.position.y>50||t.tree.position.distanceTo(camera.position)<360;t.canopy.rotation.z=Math.sin(time*.6+t.tree.position.x)*.008;}for(const p of plots)p.group.visible=(season!=='winter'||p.kind==='cabbage')&&Math.hypot(camera.position.x-(p.rect[0]+p.rect[2])/2,camera.position.z-(p.rect[1]+p.rect[3])/2)<65;for(const m of melons){if(m.regrow>0){m.regrow-=dt;m.mesh.visible=m.ripe&&m.regrow<=0;}}for(const f of fish){const a=time*f.speed+f.phase;f.g.position.set(f.cx+Math.sin(a)*f.rx,-.11+Math.sin(a*2)*.025,f.cz+Math.cos(a)*f.rz);f.g.rotation.y=Math.atan2(-Math.cos(a)*f.rx,Math.sin(a)*f.rz);f.tail.rotation.y=Math.sin(time*7+f.phase)*.3;f.g.visible=season!=='winter'&&f.g.position.distanceTo(camera.position)<110;}
      flies.visible=season==='summer'&&environment.daylight<.15&&!environment.wet;fireflies.forEach((f,i)=>flyPositions.set([f.x+Math.sin(time*.5+f.phase)*2,.5+(Math.sin(time*.7+f.phase)*.5+.5)*2,f.z+Math.cos(time*.4+f.phase)*2],i*3));flyGeo.attributes.position.needsUpdate=true;flies.material.opacity=.45+Math.sin(time*2)*.3;}
  };
}
