import * as THREE from 'three';
import {PLACES,ACTIVITY_SITES,GARDEN_PLOTS} from './places.js';

export function createMaps({host,camera,walk,onEnter}){
  const overview=document.querySelector('#entry-pins'),mini=document.querySelector('#minimap'),canvas=document.querySelector('#map-canvas'),ctx=canvas.getContext('2d');
  const background=document.createElement('canvas');background.width=480;background.height=320;const b=background.getContext('2d');
  let nav,metadata,zoom=false,target=PLACES[0],tick=0;const projected=new THREE.Vector3();
  const buttons=PLACES.map(p=>{const e=document.createElement('button');e.className='map-pin';e.dataset.entry=p.id;e.setAttribute('aria-label',`Start walking at ${p.label}`);e.innerHTML=`<span class="pin-dot" style="--pin:${p.color}">${p.icon}</span><strong>${p.label}</strong>`;e.addEventListener('click',()=>onEnter(p));overview.append(e);return e;});
  function xy(x,z){const [x0,z0,x1,z1]=nav.bounds;return [16+(x-x0)/(x1-x0)*448,16+(z-z0)/(z1-z0)*288];}
  function shape(c,zone){c.beginPath();if(zone.shape==='ellipse'){const [x,z]=xy(...zone.center),[x1,z1]=xy(zone.center[0]+zone.radius[0],zone.center[1]+zone.radius[1]);c.ellipse(x,z,x1-x,z1-z,0,0,Math.PI*2);}else{const [x,z]=xy(zone.rect[0],zone.rect[1]),[a,d]=xy(zone.rect[2],zone.rect[3]);c.rect(x,z,a-x,d-z);}c.fill();}
  function drawBackground(){b.fillStyle='#e4e8d5';b.fillRect(0,0,480,320);b.fillStyle='#aabd8a';for(const rect of metadata.fields)shape(b,{rect});b.fillStyle='#8fa76f';for(const p of GARDEN_PLOTS)shape(b,{rect:p.rect});
    b.strokeStyle='#d6cfb7';b.lineWidth=3.5;for(const x of [-426.2,-268.25,.2]){b.beginPath();b.moveTo(...xy(x,-164));b.lineTo(...xy(x,242));b.stroke();}for(const z of [-22,48.2,132,241.25]){b.beginPath();b.moveTo(...xy(-426,z));b.lineTo(...xy(.2,z));b.stroke();}b.beginPath();b.moveTo(...xy(-520,241));b.lineTo(...xy(290,241));b.stroke();
    b.fillStyle='#bac0b2';for(const [cx,cz,hx,hz,a,low,high] of nav.boxes){if(high<2||hx<.6||hz<.6)continue;const [x,z]=xy(cx,cz),sx=448/(nav.bounds[2]-nav.bounds[0]),sz=288/(nav.bounds[3]-nav.bounds[1]);b.save();b.translate(x,z);b.rotate(-a);b.fillRect(-hx*sx,-hz*sz,hx*sx*2,hz*sz*2);b.restore();}b.fillStyle='#94bfb0';nav.waterZones.forEach(v=>shape(b,v));b.fillStyle='#e8e7d7';for(const rect of nav.bridges)shape(b,{rect});}
  function update(dt){if(!nav)return;const walking=walk.enabled;mini.hidden=!walking;const rect=host.getBoundingClientRect();if(!walking){for(let i=0;i<PLACES.length;i++){const p=PLACES[i];projected.set(p.x,4,p.z).project(camera);const e=buttons[i];e.hidden=projected.z>1||Math.abs(projected.x)>1.1||Math.abs(projected.y)>1.1;e.style.left=`${(projected.x*.5+.5)*rect.width}px`;e.style.top=`${(-projected.y*.5+.5)*rect.height}px`;}}
    if(!walking||(tick-=dt)>0)return;tick=.15;ctx.clearRect(0,0,480,320);ctx.drawImage(background,0,0);const [x,z]=xy(camera.position.x,camera.position.z),[tx,tz]=xy(target.x,target.z);ctx.strokeStyle='#bc865e';ctx.setLineDash([5,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,z);ctx.lineTo(tx,tz);ctx.stroke();ctx.setLineDash([]);
    for(const p of PLACES){const [a,d]=xy(p.x,p.z);ctx.fillStyle=p===target?'#a4512e':'#576b4a';ctx.beginPath();ctx.arc(a,d,p===target?6:3,0,6.28);ctx.fill();if(zoom||p===target){ctx.font='12px system-ui';ctx.fillStyle='#283d2d';ctx.fillText(p.id==='house'?'Home':p.label,a+8,d-5);}}
    ctx.fillStyle='#a87b50';for(const s of ACTIVITY_SITES){const [a,d]=xy(s.x,s.z);ctx.fillRect(a-1,d-1,2,2);}ctx.save();ctx.translate(x,z);ctx.rotate(-camera.rotation.y);ctx.fillStyle='#24493e';ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(5,5);ctx.lineTo(0,2);ctx.lineTo(-5,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
    const distance=Math.hypot(camera.position.x-target.x,camera.position.z-target.z);document.querySelector('#map-destination').textContent=`${target.id==='house'?'Home':target.label} · ${Math.round(distance)} m`;host.dataset.mapTarget=target.id;host.dataset.homeDistance=Math.round(Math.hypot(camera.position.x+32,camera.position.z-109));}
  document.querySelector('#map-expand').addEventListener('click',()=>{zoom=!zoom;mini.classList.toggle('expanded',zoom);document.querySelector('#map-expand').setAttribute('aria-expanded',String(zoom));tick=0;});
  canvas.addEventListener('click',e=>{if(!nav)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*480,z=(e.clientY-rect.top)/rect.height*320;target=PLACES.reduce((best,p)=>{const a=xy(p.x,p.z),d=Math.hypot(a[0]-x,a[1]-z);return d<best.d?{p,d}:best;},{p:target,d:Infinity}).p;tick=0;});
  document.querySelector('#map-home').addEventListener('click',()=>{target=PLACES[0];tick=0;});
  return {install(data,meta){nav=data;metadata=meta;drawBackground();update(1);},update,home(){target=PLACES[0];tick=0;},get target(){return target;}};
}
