import * as THREE from 'three';
import {PLACES,ACTIVITY_SITES,GARDEN_PLOTS,ACTIVITY_TYPES,activitySpawn} from './places.js';
import {siteAvailable} from './game/adventure.js';
import {shoreX} from './coast-layout.js';

export function createMaps({host,camera,walk,environment,onEnter}){
  const overview=document.querySelector('#entry-pins'),mini=document.querySelector('#minimap'),canvas=document.querySelector('#map-canvas'),ctx=canvas.getContext('2d');
  const background=document.createElement('canvas');background.width=480;background.height=320;const b=background.getContext('2d');
  let nav,metadata,zoom=false,target=PLACES[0],tick=0;const projected=new THREE.Vector3();
  const buttons=PLACES.map(p=>{const e=document.createElement('button');e.className='map-pin';e.dataset.entry=p.id;e.setAttribute('aria-label',`Start walking at ${p.label}`);e.innerHTML=`<span class="pin-dot" style="--pin:${p.color}">${p.icon}</span><strong>${p.label}</strong>`;e.addEventListener('click',()=>onEnter(p));overview.append(e);return e;});
  const activityPin=document.createElement('button');activityPin.className='activity-pin';activityPin.hidden=true;overview.append(activityPin);
  activityPin.addEventListener('click',()=>{const place=activitySpawn(nav,target);if(place)onEnter({place,label:target.label});});
  const legend=document.querySelector('#map-activities');
  const activityButtons=Object.entries(ACTIVITY_TYPES).map(([kind,type])=>{const e=document.createElement('button');e.dataset.mapActivity=kind;e.title=`${type.label} · ${type.hint}`;e.innerHTML=`<span style="color:${type.color}">${type.icon}</span>${type.label}`;e.addEventListener('click',()=>{const origin=walk.enabled?camera.position:PLACES[0];target=ACTIVITY_SITES.filter(s=>s.kind===kind).sort((a,b)=>Math.hypot(a.x-origin.x,a.z-origin.z)-Math.hypot(b.x-origin.x,b.z-origin.z))[0];tick=0;});legend.append(e);return e;});
  function xy(x,z){const [x0,z0,x1,z1]=nav.bounds;return [16+(x-x0)/(x1-x0)*448,16+(z-z0)/(z1-z0)*288];}
  function shape(c,zone){c.beginPath();if(zone.shape==='ellipse'){const [x,z]=xy(...zone.center),[x1,z1]=xy(zone.center[0]+zone.radius[0],zone.center[1]+zone.radius[1]);c.ellipse(x,z,x1-x,z1-z,0,0,Math.PI*2);}else{const [x,z]=xy(zone.rect[0],zone.rect[1]),[a,d]=xy(zone.rect[2],zone.rect[3]);c.rect(x,z,a-x,d-z);}c.fill();}
  function drawBackground(){b.fillStyle='#e4e8d5';b.fillRect(0,0,480,320);b.fillStyle='#aabd8a';for(const rect of metadata.fields)shape(b,{rect});b.fillStyle='#8fa76f';for(const p of GARDEN_PLOTS)shape(b,{rect:p.rect});
    if(nav.woodland){b.fillStyle='#759c79';shape(b,{rect:nav.woodland.rect});b.fillStyle='#426e58';for(const p of nav.woodlandTrees){const [x,z]=xy(p.x,p.z);b.beginPath();b.arc(x,z,1.5,0,6.28);b.fill();}b.strokeStyle='#ecd7a4';b.lineWidth=2;b.beginPath();nav.woodland.trail.forEach(([x,z],i)=>i?b.lineTo(...xy(x,z)):b.moveTo(...xy(x,z)));b.stroke();}
    if(nav.coast){b.fillStyle='#9faf82';shape(b,{rect:[300,nav.bounds[1],nav.bounds[2],nav.bounds[3]]});for(const [offset,color] of [[-35,'#e5d2a5'],[0,'#72babc']]){b.fillStyle=color;b.beginPath();b.moveTo(...xy(nav.bounds[2],nav.bounds[1]));for(let z=nav.bounds[1];z<=nav.bounds[3];z+=3)b.lineTo(...xy(shoreX(z)+offset,z));b.lineTo(...xy(nav.bounds[2],nav.bounds[3]));b.closePath();b.fill();}b.strokeStyle='#efead5';b.lineWidth=1.5;b.beginPath();for(let z=nav.bounds[1];z<=nav.bounds[3];z+=3)b.lineTo(...xy(shoreX(z)+5,z));b.stroke();b.strokeStyle='#ecd7a4';b.beginPath();nav.coastTrail.forEach(([x,z],i)=>i?b.lineTo(...xy(x,z)):b.moveTo(...xy(x,z)));b.stroke();}
    b.strokeStyle='#d6cfb7';b.lineWidth=3.5;for(const x of [-426.2,-268.25,.2]){b.beginPath();b.moveTo(...xy(x,-164));b.lineTo(...xy(x,242));b.stroke();}for(const z of [-22,48.2,132,241.25]){b.beginPath();b.moveTo(...xy(-426,z));b.lineTo(...xy(.2,z));b.stroke();}b.beginPath();b.moveTo(...xy(-520,241));b.lineTo(...xy(290,241));b.stroke();
    b.fillStyle='#bac0b2';for(const [cx,cz,hx,hz,a,low,high] of nav.boxes){if(high<2||hx<.6||hz<.6)continue;const [x,z]=xy(cx,cz),sx=448/(nav.bounds[2]-nav.bounds[0]),sz=288/(nav.bounds[3]-nav.bounds[1]);b.save();b.translate(x,z);b.rotate(-a);b.fillRect(-hx*sx,-hz*sz,hx*sx*2,hz*sz*2);b.restore();}b.fillStyle='#94bfb0';nav.waterZones.forEach(v=>shape(b,v));b.fillStyle='#e8e7d7';for(const rect of nav.bridges)shape(b,{rect});}
  function update(dt){if(!nav)return;const walking=walk.enabled;mini.hidden=false;mini.classList.toggle('on-overview',!walking);const rect=host.getBoundingClientRect();if(!walking){for(let i=0;i<PLACES.length;i++){const p=PLACES[i];projected.set(p.x,4,p.z).project(camera);const e=buttons[i];e.hidden=projected.z>1||Math.abs(projected.x)>1.1||Math.abs(projected.y)>1.1;e.style.left=`${(projected.x*.5+.5)*rect.width}px`;e.style.top=`${(-projected.y*.5+.5)*rect.height}px`;}}
    activityPin.hidden=walking||!target.kind;if(!activityPin.hidden){const t=ACTIVITY_TYPES[target.kind];activityPin.innerHTML=`<span class="pin-dot" style="--pin:${t.color}">${t.icon}</span><strong>${target.label} · enter</strong>`;projected.set(target.x,3,target.z).project(camera);activityPin.hidden=projected.z>1||Math.abs(projected.x)>1||Math.abs(projected.y)>1;activityPin.style.left=`${(projected.x*.5+.5)*rect.width}px`;activityPin.style.top=`${(-projected.y*.5+.5)*rect.height}px`;activityPin.dataset.activityEntry=target.id;}
    if((tick-=dt)>0)return;tick=.15;ctx.clearRect(0,0,480,320);ctx.drawImage(background,0,0);const origin=walking?camera.position:PLACES[0],[x,z]=xy(origin.x,origin.z),[tx,tz]=xy(target.x,target.z);ctx.strokeStyle='#bc865e';ctx.setLineDash([5,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,z);ctx.lineTo(tx,tz);ctx.stroke();ctx.setLineDash([]);
    for(const p of PLACES){const [a,d]=xy(p.x,p.z);ctx.fillStyle=p===target?'#a4512e':'#576b4a';ctx.beginPath();ctx.arc(a,d,p===target?6:3,0,6.28);ctx.fill();if(zoom||p===target){ctx.font='12px system-ui';ctx.fillStyle='#283d2d';ctx.fillText(p.id==='house'?'Home':p.label,a+8,d-5);}}
    for(const s of ACTIVITY_SITES){const [a,d]=xy(s.x,s.z),type=ACTIVITY_TYPES[s.kind],selected=s.id===target.id;ctx.globalAlpha=siteAvailable(s,environment)?1:.45;ctx.fillStyle=selected?'#fff5ce':'#35574a';ctx.beginPath();ctx.arc(a,d,selected?10:6,0,6.28);ctx.fill();ctx.strokeStyle=type.color;ctx.lineWidth=selected?2:1;ctx.stroke();ctx.font=`bold ${selected?15:11}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=selected?'#284a35':type.color;ctx.fillText(type.icon,a,d);ctx.globalAlpha=1;if(selected){ctx.font='bold 12px system-ui';ctx.textAlign='left';ctx.fillStyle='#254232';ctx.fillText(s.label,a+13,d-10);}}
    ctx.textAlign='left';ctx.textBaseline='alphabetic';if(walking){ctx.save();ctx.translate(x,z);ctx.rotate(-camera.rotation.y);ctx.fillStyle='#24493e';ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(5,5);ctx.lineTo(0,2);ctx.lineTo(-5,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
    for(const e of activityButtons){e.classList.toggle('selected',target.kind===e.dataset.mapActivity);e.classList.toggle('unavailable',!ACTIVITY_SITES.some(s=>s.kind===e.dataset.mapActivity&&siteAvailable(s,environment)));e.setAttribute('aria-pressed',String(target.kind===e.dataset.mapActivity));}
    const distance=Math.hypot(origin.x-target.x,origin.z-target.z);document.querySelector('#map-destination').textContent=`${target.id==='house'?'Home':target.label}${walking?` · ${Math.round(distance)} m`:''}`;host.dataset.mapTarget=target.id;host.dataset.activityMarkers=String(ACTIVITY_SITES.length);host.dataset.homeDistance=Math.round(Math.hypot(camera.position.x+32,camera.position.z-109));}
  document.querySelector('#map-expand').addEventListener('click',()=>{zoom=!zoom;mini.classList.toggle('expanded',zoom);document.querySelector('#map-expand').setAttribute('aria-expanded',String(zoom));tick=0;});
  canvas.addEventListener('click',e=>{if(!nav)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*480,z=(e.clientY-rect.top)/rect.height*320;target=[...PLACES,...ACTIVITY_SITES].reduce((best,p)=>{const a=xy(p.x,p.z),d=Math.hypot(a[0]-x,a[1]-z);return d<best.d?{p,d}:best;},{p:target,d:Infinity}).p;tick=0;});
  document.querySelector('#map-home').addEventListener('click',()=>{target=PLACES[0];tick=0;});
  return {install(data,meta){nav=data;metadata=meta;drawBackground();update(1);},update,home(){target=PLACES[0];tick=0;},get target(){return target;}};
}
