import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export const seeded=(seed=531)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
export const material=color=>new THREE.MeshStandardMaterial({color,roughness:.87,side:THREE.DoubleSide});
const ball=new THREE.SphereGeometry(1,12,8);
export function oval(root,p,s,mat){const o=new THREE.Mesh(ball,mat);o.position.set(...p);o.scale.set(...s);root.add(o);return o;}
export function stem(root,points,r,mat){const o=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),8,r,4,false),mat);root.add(o);return o;}
// A cupped, twisted leaf surface, with a pointed tip and a raised midrib (not a cutout plane).
export function leafGeometry(w=.12,h=.26,lobes=0){const v=[],uv=[],idx=[];for(let j=0;j<=8;j++){const t=j/8,width=Math.sin(Math.PI*t)**.7*w*(1+lobes*Math.sin(t*5*Math.PI));for(let k=0;k<3;k++){const s=k-1;v.push(s*width,Math.sin(t*Math.PI)*h*.16+s*s*w*.24,t*h);uv.push((s+1)/2,t);if(j<8&&k<2){const a=j*3+k;idx.push(a,a+1,a+3,a+1,a+4,a+3);}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g;}
export function leaf(root,p,w,h,turn,mat,lobes=0,tilt=.2){const o=new THREE.Mesh(leafGeometry(w,h,lobes),mat);o.position.set(...p);o.rotation.set(tilt,turn,(turn%1-.5)*.2);root.add(o);return o;}
// Lotus leaves have a broad, rippled circular surface on an upright stalk.
export function lotusLeaf(radius=.4){const v=[0,0,0],idx=[];for(let j=1;j<=3;j++)for(let k=0;k<20;k++){const a=k/20*Math.PI*2,rr=radius*j/3;v.push(Math.cos(a)*rr,.07*(j/3)**2+Math.sin(a*5)*.015*j/3,Math.sin(a)*rr);const n=1+(j-1)*20+k,next=1+(j-1)*20+(k+1)%20;if(j===1)idx.push(0,next,n);else{const prev=n-20,pnext=next-20;idx.push(prev,pnext,n,pnext,next,n);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();return g;}
export function merged(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(o.matrixWorld);if(!groups.has(o.material))groups.set(o.material,[]);groups.get(o.material).push(g.index?g.toNonIndexed():g);});const out=new THREE.Group();for(const [mat,parts] of groups){const g=mergeGeometries(parts),m=new THREE.Mesh(g,mat);m.castShadow=true;m.receiveShadow=true;out.add(m);parts.forEach(p=>p.dispose());}return out;}
export function instances(template,placements){const root=new THREE.Group(),temp=new THREE.Object3D();for(const mesh of template.children){const m=new THREE.InstancedMesh(mesh.geometry,mesh.material,placements.length);placements.forEach((p,i)=>{temp.position.set(p.x,p.y??.1,p.z);temp.rotation.set(p.tilt??0,p.angle??0,p.roll??0);temp.scale.setScalar(p.scale??1);temp.updateMatrix();m.setMatrixAt(i,temp.matrix);if(p.tint)m.setColorAt(i,p.tint);});m.computeBoundingSphere();m.castShadow=true;m.receiveShadow=true;root.add(m);}return root;}
