import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {createGardens} from './gardens.js';
import {GARDEN_PLOTS} from './places.js';
import {createPlantingMask} from './planting.js';
import {paintedMaterial} from './painted.js';

// Seeded, original surface textures. No third-party photo assets or network requests during play.
function rng(seed=71){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),r=rng(114);x.fillStyle='#d1cec6';x.fillRect(0,0,256,256);
  for(let i=0;i<13000;i++){const v=140+r()*110;x.fillStyle=`rgba(${v},${v},${v},${.08+r()*.22})`;x.fillRect(r()*256,r()*256,r()*3+.3,r()*3+.3);}
  if(kind==='brick'||kind==='tile'){const h=kind==='tile'?24:32,w=kind==='tile'?30:84;for(let y=0;y<256;y+=h){x.strokeStyle='#7a7770';x.lineWidth=2;x.beginPath();x.moveTo(0,y);x.lineTo(256,y);x.stroke();for(let a=-w;a<256+w;a+=w){const b=a+(Math.floor(y/h)%2)*w/2;x.beginPath();x.moveTo(b,y);x.lineTo(b,y+h);x.stroke();}}}
  if(kind==='bark'){for(let i=0;i<120;i++){x.strokeStyle=`rgba(45,38,28,${r()*.6})`;x.lineWidth=.5+r()*2;x.beginPath();const a=r()*256,b=r()*256;x.moveTo(a,b);x.lineTo(a+4*r(),b+10+r()*50);x.stroke();}}
  const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;
}
function cropTexture(maize){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),r=rng(761);for(let i=0;i<(maize?8:55);i++){const px=8+r()*240,h=130+r()*115,y=256-h,v=160+r()*90;x.strokeStyle=`rgb(${v*.82},${v},${v*.62})`;x.fillStyle=x.strokeStyle;x.lineWidth=maize?2:1;x.beginPath();x.moveTo(px,256);x.quadraticCurveTo(px+6,y+h*.5,px,y);x.stroke();for(let j=0;j<(maize?7:3);j++){const py=230-j*(maize?22:34),s=j%2?1:-1,w=maize?55:25;x.beginPath();x.moveTo(px,py);x.bezierCurveTo(px+s*w*.3,py-12,px+s*w*.7,py-30,px+s*w,py+4);x.bezierCurveTo(px+s*w*.6,py-8,px+s*w*.2,py-4,px,py);x.fill();}if(!maize){x.fillStyle=`rgb(${v*.93},${v},${v*.65})`;for(let j=0;j<7;j++){x.beginPath();x.ellipse(px+(j%2?2:-2),y+j*3,2,3,j%2?.4:-.4,0,6.28);x.fill();x.beginPath();x.moveTo(px,y+j*3);x.lineTo(px+(j%2?6:-6),y+j*3-8);x.stroke();}}}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function blade(height,width,reach,turn=0,base=0){const v=[],uv=[],idx=[];for(let j=0;j<=7;j++){const t=j/7,a=Math.sin(t*Math.PI/2)*reach,b=base+Math.sin(t*2.1)*height,w=width*Math.sin(Math.PI*(t*.94+.03));for(const s of [-1,1]){v.push(a*Math.sin(turn)+s*w*Math.cos(turn),b,a*Math.cos(turn)-s*w*Math.sin(turn));uv.push(s===1?1:0,t);}if(j<7){const k=j*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g;}
function plant(maize){const parts=[];for(let j=0;j<(maize?7:10);j++)parts.push(blade(maize?.36:.48,maize?.065:.017,maize?.63:.14,j*2.399,maize?.25+j*.20:0));
  if(maize){const stem=new THREE.CylinderGeometry(.015,.025,1.85,5,1);stem.translate(0,.92,0);parts.push(stem);const cob=new THREE.SphereGeometry(.065,6,5);cob.scale(.7,2.5,.7);cob.translate(.06,1.2,.03);parts.push(cob);for(let j=0;j<4;j++)parts.push(blade(.15,.005,.15,j*1.57,1.82));}
  else{for(let j=0;j<7;j++){const a=j*2.4,y=.46+(j%4)*.04,x=Math.sin(a)*.10,z=Math.cos(a)*.10;const stem=new THREE.CylinderGeometry(.005,.006,y,4,1);stem.translate(x,y/2,z);parts.push(stem);const head=new THREE.SphereGeometry(.024,5,4);head.scale(1,3.5,1);head.translate(x,y,z);parts.push(head);}}
  const g=mergeGeometries(parts);parts.forEach(p=>p.dispose());return g;
}
function wind(material,strength=.07){material.userData.clock={value:0};material.onBeforeCompile=s=>{s.uniforms.windTime=material.userData.clock;s.vertexShader='uniform float windTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\n transformed.x+=sin(windTime*1.7+position.y*2.0+instanceMatrix[3].x*.3)*pow(max(position.y,0.0),1.2)*${strength.toFixed(3)};`);};material.customProgramCacheKey=()=>`wind-${strength}`;}
function openWaterbed(material,nav){material.userData.paintGround=false;const f=n=>Number(n).toFixed(3),cut=(nav.waterZones||[]).map(zone=>{if(zone.shape==='ellipse'){const [x,z]=zone.center,[a,b]=zone.radius;return `if(length((waterWorld.xz-vec2(${f(x)},${f(z)}))/vec2(${f(a)},${f(b)}))<.98)discard;`;}const [x,z,a,b]=zone.rect;return `if(waterWorld.x>${f(x)}&&waterWorld.x<${f(a)}&&waterWorld.z>${f(z)}&&waterWorld.z<${f(b)})discard;`;}).join('\n');material.onBeforeCompile=s=>{s.vertexShader='varying vec3 waterWorld;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nwaterWorld=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader='varying vec3 waterWorld;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>\n${cut}`);};material.customProgramCacheKey=()=>`waterbed-${cut}`;material.needsUpdate=true;}
export function createWorldDetails({scene,camera,host,environment}){
  const root=new THREE.Group();root.name='Living fields';scene.add(root);let treeLeaves,crops=[],waterMats=[],season='green',gardens;const temps=new THREE.Object3D(),r=rng(521);const surfaces={plaster:texture('plaster'),brick:texture('brick'),tile:texture('tile'),concrete:texture('concrete'),bark:texture('bark')};
  function install(model,data,nav){root.clear();crops=[];waterMats=[];const mask=createPlantingMask(nav,nav.roads||data.roads);
    model.traverse(o=>{if(!o.isMesh)return;const m=o.material,n=m?.name||'';
      if(/poplar foliage|crop rows|dry corn leaves|::V \| leaf \d/.test(n)){o.userData.replacedVegetation=true;o.visible=false;}
      let t=/brick/i.test(n)?surfaces.brick:/roof tiles|brown roof/i.test(n)?surfaces.tile:/bark/.test(n)?surfaces.bark:/plaster|white tile facade/.test(n)?surfaces.plaster:/concrete|paving/.test(n)?surfaces.concrete:null;
      if(/green field$|corn field floor/.test(n))t=surfaces.concrete;
      if(t){m.map=t;m.bumpMap=t;m.bumpScale=/brick|tile/.test(n)?.025:.012;m.needsUpdate=true;}
      if(/::MAP \| (earth|bank grasses)$/.test(n))openWaterbed(m,nav);
      if(/still canal water/.test(n)){const w=waterMaterial();o.material=w;waterMats.push(w);}
      o.castShadow=!o.userData.season&&!/glass|water|wire|field|crop|foliage/.test(n);o.receiveShadow=!/glass|water/.test(n);
    });
    // Denser narrow crowns, shaped individual leaves within each cutout, and empty winter branches.
    const leafMat=paintedMaterial('foliage','#cad9b6');wind(leafMat,.012);
    const positions=[];for(const [x,z,h] of data.trees){for(let i=0;i<48;i++){const a=r()*6.28,y=4+r()*(h-4),rr=Math.sqrt(r())*(1.1+2*Math.sin((y-4)/(h-4)*Math.PI));positions.push([x+Math.cos(a)*rr,y,z+Math.sin(a)*rr,1.25+r()*.8,r()*6.28]);}}
    treeLeaves=new THREE.InstancedMesh(new THREE.PlaneGeometry(2.5,2.5),leafMat,positions.length);treeLeaves.name='Poplar leaf clusters';for(let i=0;i<positions.length;i++){const [x,y,z,s,a]=positions[i];temps.position.set(x,y,z);temps.rotation.set((r()-.5)*1.2,a,(r()-.5)*.8);temps.scale.setScalar(s);temps.updateMatrix();treeLeaves.setMatrixAt(i,temps.matrix);}treeLeaves.computeBoundingSphere();root.add(treeLeaves);
    treeLeaves.castShadow=true;treeLeaves.receiveShadow=true;
    const ivy=new THREE.InstancedMesh(new THREE.PlaneGeometry(.45,.45),leafMat,1000);ivy.name='Ivy on the lane wall';for(let i=0;i<1000;i++){temps.position.set(-40.04+r()*.15,.25+r()*3.15,98.5+r()*23);temps.rotation.set(0,Math.PI/2,(r()-.5)*1.2);temps.scale.setScalar(.65+r()*.65);temps.updateMatrix();ivy.setMatrixAt(i,temps.matrix);}ivy.computeBoundingSphere();root.add(ivy);
    const wheat=plant(false),maize=plant(true);
    const coverTextures={wheat:cropTexture(false),maize:cropTexture(true)},p1=new THREE.PlaneGeometry(1.3,.8);p1.translate(0,.4,0);const p2=p1.clone();p2.rotateY(Math.PI/2);const coverGeo=mergeGeometries([p1,p2]);
    // Chunking preserves camera culling. Plants grow in uneven rows rather than painted stripes.
    for(const rect of data.fields){const [x0,z0,x1,z1]=rect;for(let x=x0;x<x1;x+=32)for(let z=z0;z<z1;z+=32){const pts=[];for(let xx=x+.4;xx<Math.min(x+32,x1);xx+=.95)for(let zz=z+.4;zz<Math.min(z+32,z1);zz+=.85){const px=xx+(r()-.5)*.62,pz=zz+(r()-.5)*.72;if(mask.onRoad(px,pz,.3)||mask.inWater(px,pz,.25)||GARDEN_PLOTS.some(({rect:[a,b,c,d]})=>px>a-.5&&px<c+.5&&pz>b-.5&&pz<d+.5)||r()<.035+Math.max(0,Math.sin(px*.13)*Math.cos(pz*.12))*.10)continue;pts.push([px,pz,r()]);}
      const mat=new THREE.MeshStandardMaterial({color:'#799644',side:THREE.DoubleSide,roughness:.92});wind(mat,.035);const mesh=new THREE.InstancedMesh(wheat,mat,pts.length);mesh.name='Seasonal crop patch';for(let i=0;i<pts.length;i++){const [px,pz,v]=pts[i];temps.position.set(px,.16,pz);temps.rotation.set(0,v*6.28,0);temps.scale.setScalar(.8+v*.5);temps.updateMatrix();mesh.setMatrixAt(i,temps.matrix);mesh.setColorAt(i,new THREE.Color().setHSL(.23,.36,.38+v*.09));}mesh.computeBoundingSphere();root.add(mesh);
      const cm=new THREE.MeshStandardMaterial({map:coverTextures.wheat,side:THREE.DoubleSide,alphaTest:.45,roughness:1,color:'#b7c394'});wind(cm,.025);const cover=new THREE.InstancedMesh(coverGeo,cm,pts.length);cover.name='Dense crop stand';cover.instanceMatrix=mesh.instanceMatrix;cover.computeBoundingSphere();root.add(cover);crops.push({mesh,wheat,maize,mat,cover,coverTextures});}}
    for(const zone of nav.woodland?.ponds||[]){const mat=waterMaterial(),pond=new THREE.Mesh(new THREE.CircleGeometry(1,96),mat);pond.rotation.x=-Math.PI/2;pond.scale.set(...zone.radius,1);pond.position.set(zone.center[0],.055,zone.center[1]);pond.name=zone.name;root.add(pond);waterMats.push(mat);}
    addReeds(nav,mask);gardens=createGardens({parent:root,scene,environment,nav});host.dataset.gardenKinds=GARDEN_PLOTS.map(p=>p.kind).join(',');host.dataset.fishSpecies=[...new Set(gardens.fish.map(f=>f.kind))].join(',');host.dataset.bigTrees=String(gardens.trees.length);host.dataset.frogs=String(gardens.wetland.frogs.length);host.dataset.roadFootprints=String(data.roads.length);host.dataset.treeRoadConflicts=String(gardens.trees.filter(t=>mask.onRoad(t.tree.position.x,t.tree.position.z,.8)).length);host.dataset.treeClusters=String(positions.length);host.dataset.cropPatches=String(crops.length);setSeason(season);
  }
  function addReeds(nav,mask){const geom=mergeGeometries([blade(.65,.022,.20),blade(.5,.022,.2,2),blade(.7,.015,.12,4)]),m=new THREE.MeshStandardMaterial({color:'#797f49',side:THREE.DoubleSide,roughness:1});wind(m,.025);const pts=[];
    for(const zone of nav.waterZones||[]){if(zone.shape==='ellipse'){for(let i=0;i<120;i++){const a=i/120*6.28;pts.push([zone.center[0]+Math.cos(a)*(zone.radius[0]+.9),zone.center[1]+Math.sin(a)*(zone.radius[1]+.9)]);}}else{const [x0,z0,x1,z1]=zone.rect;if(x1-x0>z1-z0){for(let x=x0;x<x1;x+=2.5)for(const z of [z0-.7,z1+.7])pts.push([x,z]);}else{for(let z=z0;z<z1;z+=2.5)for(const x of [x0-.7,x1+.7])pts.push([x,z]);}}}
    const safePts=pts.filter(([x,z])=>mask.land(x,z,.4));const reeds=new THREE.InstancedMesh(geom,m,safePts.length);safePts.forEach(([x,z],i)=>{temps.position.set(x,.1,z);temps.rotation.set(0,r()*6.28,0);temps.scale.setScalar(.7+r()*.7);temps.updateMatrix();reeds.setMatrixAt(i,temps.matrix);});reeds.computeBoundingSphere();root.add(reeds);
  }
  function setSeason(value){season=value;gardens?.setSeason(value);if(treeLeaves){treeLeaves.visible=value!=='winter';treeLeaves.material.color.set(value==='corn'?'#d4ba83':'#cad9b6');}for(const p of crops){const corn=value==='summer'||value==='corn';p.mesh.geometry=corn?p.maize:p.wheat;p.mesh.material.color.set(value==='corn'?'#c3a66a':value==='summer'?'#538744':'#91a959');p.mesh.scale.y=value==='winter'?.25:1;p.mesh.position.y=.16*(1-p.mesh.scale.y);p.mesh.computeBoundingSphere();p.cover.material.map=corn?p.coverTextures.maize:p.coverTextures.wheat;p.cover.material.color.set(value==='corn'?'#d1b177':'#b7c394');p.cover.material.needsUpdate=true;p.cover.scale.y=value==='winter'?.2:corn?2.3:1;p.cover.position.y=.16*(1-p.cover.scale.y);}host.dataset.livingSeason=value;}
  function waterMaterial(){return new THREE.ShaderMaterial({fog:true,transparent:true,depthWrite:false,uniforms:{...THREE.UniformsLib.fog,time:{value:0},day:{value:1},rain:{value:0},ice:{value:0},skyColor:{value:new THREE.Color('#adc6ce')}},vertexShader:`varying vec3 p;varying vec3 eye;#include <fog_pars_vertex>
void main(){vec4 w=modelMatrix*vec4(position,1.);p=w.xyz;eye=cameraPosition-w.xyz;vec4 mvPosition=viewMatrix*w;gl_Position=projectionMatrix*mvPosition;#include <fog_vertex>
}`.replaceAll(';#include',';\n#include'),fragmentShader:`uniform float time;uniform float day;uniform float rain;uniform float ice;uniform vec3 skyColor;varying vec3 p;varying vec3 eye;#include <fog_pars_fragment>
void main(){float warp=sin(p.z*.9+p.x*.3+time*.3)*1.5;float a=sin(p.x*3.4+p.z*1.3+warp-time*1.4),b=sin(p.z*4.5-p.x*.8+warp-time*1.9);vec3 n=normalize(vec3(a*.065,1.,b*.055));float f=pow(1.-max(dot(normalize(eye),n),0.),3.)*.6;float shimmer=pow(max(0.,sin(p.x*5.+p.z*2.+warp-time*2.)),12.)*.11;float ripple=sin(length(mod(p.xz,vec2(1.7))-vec2(.85))*26.-time*9.)*rain*.012;vec3 deep=vec3(.16,.38,.29);vec3 c=mix(deep,skyColor*.55,f)+vec3(shimmer+ripple);c=mix(c,vec3(.46,.55,.54),ice);gl_FragColor=vec4(c*(.20+.80*day),mix(.77,.96,ice));#include <tonemapping_fragment>
#include <colorspace_fragment>
#include <fog_fragment>
}`.replaceAll(';#include',';\n#include')});}
  return {install,setSeason,root,get gardens(){return gardens;},update(dt,time){gardens?.update(dt,time,camera);for(const p of crops){const b=p.mesh.boundingSphere,d=Math.hypot(camera.position.x-b.center.x,camera.position.z-b.center.z);p.mesh.visible=d<32+b.radius*.2;p.cover.visible=d>=32&&d<140+b.radius*.3;}root.traverse(o=>{if(o.material?.userData.clock)o.material.userData.clock.value=time;});for(const m of waterMats){m.uniforms.time.value=time;m.uniforms.day.value=environment.daylight;m.uniforms.rain.value=environment.wet?1:0;m.uniforms.ice.value=season==='winter'?.55:0;m.uniforms.skyColor.value.copy(scene.background);}}};
}
